### ISSUE TITLE
refField option not working as expected for useDocumentData

### ISSUE THREAD

**Issue by m4cbeth** [CSFrequency/react-firebase-hooks#100]
Hello there, love these hooks and thank you so much for them!

But I'm trying to use useDocumentData(query, {refField: "whatever"}) as my understanding is that this would add a property of "whatever" with a ref to the document I'm getting data from. However it's not currently doing so!

**Comment by m4cbeth** [comment]
![image](https://user-images.githubusercontent.com/56993541/105531034-f41f8e00-5ca5-11eb-86cf-16efce9c0dac.png)

I thought I'd add this if it might be helpful!

**Comment by chrisbianca** [comment]
This is due to the documentation being displayed on GitHub referencing the master branch where this functionality exists. A new version of the library which includes this functionality will be released soon.

**Comment by m4cbeth** [comment]
Thank you very much for the clarification Chris! I very much appreciate you taking the time to give some guidance to a lost little noob haha. Thanks again Chris.
