### ISSUE TITLE
Bug(?): Unable to install firebase hooks

### ISSUE THREAD

**Issue by oof2win2** [CSFrequency/react-firebase-hooks#102]
While installing with the command `npm install --save react-firebase-hooks`, I got the following error. I used `npm create-react-app <appName>` to create an app beforehand, but I wasn't able install react firebase hooks after that. I believe that this is a bug, however I am not entirely sure.
```
❯ npm install --save react-firebase-hooks
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-database-project@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-firebase-hooks@2.2.0
npm ERR! node_modules/react-firebase-hooks
npm ERR!   react-firebase-hooks@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/oof2win2/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oof2win2/.npm/_logs/2021-01-30T19_46_11_639Z-debug.log
```
[2021-01-30T19_46_11_639Z-debug.log](https://github.com/CSFrequency/react-firebase-hooks/files/5898617/2021-01-30T19_46_11_639Z-debug.log)

**Comment by lorstenoplo** [comment]
All these dependency issues are common while using npm
If you don't mind can try creating and installing all the packages with yarn once

**Comment by oof2win2** [comment]
Yup, yarn made it work. It only threw this warning, which can be ignored i guess
`warning " > react-firebase-hooks@2.2.0" has incorrect peer dependency "react@^16.8.0"`

**Comment by lorstenoplo** [comment]
Close this issue as it is solved
