### ISSUE TITLE
Performance: Every hook creates its own listener?

### ISSUE THREAD

**Issue by pdme** [CSFrequency/react-firebase-hooks#103]
I'm wondering if every time I use a firebase hook, say `useAuth`, it creates a separate internal state and a separate listener.

I'm guessing it is? And if so, does that not raise performance issues since both hooks will separately talk to the firebase API?

Also, as a result, the two hook instances at some point for a short time might have differing states, which may cause stability issues?

**Comment by matamatanot** [comment]
Some performance issues have been resolved by #79.

**Comment by chrisbianca** [comment]
@pdme You are correct that each hook manages its own internal state, however, there are already optimisations built into the Firebase client library to ensure that unnecessary network requests aren't made for information that is already known to the client.

Auth is slightly different and there may be some benefit to adopting a context provider approach, but as yet it's not caused anybody any issues. I'm going to close this for now.
