### ISSUE TITLE
Cannot install because of dependency error on React 17.0.1

### ISSUE THREAD

**Issue by sg1705** [CSFrequency/react-firebase-hooks#104]
I am trying to install react-firehose-hooks but I keep getting a dependency error. Here's the error message.

I suspect that the dependency hasn't been updated to the latest version of React.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: extension@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-firebase-hooks@2.2.0
npm ERR! node_modules/react-firebase-hooks
npm ERR!   react-firebase-hooks@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
```

**Comment by lorstenoplo** [comment]
All these dependency issues are common while using npm
If you don't mind can try creating and installing all the packages with yarn once

**Comment by chrisbianca** [comment]
This has been resolved in the latest version on master which will be released soon
