### ISSUE TITLE
Incorrect for the type of the first value in array that is return value of the `useAuthState` hooks?

### ISSUE THREAD

**Issue by kqito** [CSFrequency/react-firebase-hooks#106]
I have a question about the type of the first value in array that is return value of the `useAuthState` hooks.

the its type is `User | undefined`, but the type of return value of  `firebase.auth()` is `firebase.User | null`, so I think it should be `firebase.User | undefined | null`.

If this is a bug I will fix the following as a PR

- Fix generic type of [useLoadingValue](https://github.com/CSFrequency/react-firebase-hooks/blob/master/util/useLoadingValue.ts#L56)
- Fix the type of [useLoadingValue](https://github.com/CSFrequency/react-firebase-hooks/blob/master/auth/useAuthState.ts#L9) in the AuthStateHook file

Thanks for the great library!

**Comment by chrisbianca** [comment]
This has now been fixed as #107
