### ISSUE TITLE
Publish new version on NPM

### ISSUE THREAD

**Issue by Godefroy** [CSFrequency/react-firebase-hooks#109]
Hi,

The current version on NPM doesn't seem up to date and I have errors while building my webapp with Typescript:

![image](https://user-images.githubusercontent.com/148421/108089249-ae25d200-7079-11eb-9f0e-d6a0a5a21112.png)

![image](https://user-images.githubusercontent.com/148421/108088996-64d58280-7079-11eb-8912-4d2c5cbd570f.png)

Could you please publish a new version on NPM?

PS: Thanks a lot for this package, that's great!

**Comment by jayp0521** [comment]
+1, I would appreciate an update as well

**Comment by klutchdev** [comment]
+2!

```shell
npm install --save react-firebase-hooks
```

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxxxxx.app@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-firebase-hooks@2.2.0
npm ERR! node_modules/react-firebase-hooks
npm ERR!   react-firebase-hooks@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by lorstenoplo** [comment]
> +2!
> 
> ```shell
> npm install --save react-firebase-hooks
> ```
> 
> ```shell
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: xxxxxx.app@1.0.0
> npm ERR! Found: react@17.0.1
> npm ERR! node_modules/react
> npm ERR!   react@"17.0.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0" from react-firebase-hooks@2.2.0
> npm ERR! node_modules/react-firebase-hooks
> npm ERR!   react-firebase-hooks@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ```

Try with yarn, but yeah it's a problem I agree

**Comment by jayp0521** [comment]
I did `npm i --force` and it seems to work fine

**Comment by jayp0521** [comment]
If the peer dependency is updated to react: ">= 16 || ^17" everything should work fine

**Comment by jayp0521** [comment]
> If the peer dependency is updated to react: ">= 16 || ^17" everything should work fine

**Comment by mauriceackel** [comment]
@jayp0521 Your issue comes from the fact that you are using the next major version of react (i.e. 17.X) and this library is not released for this version yet. There might be breaking changes in vision 17 that impact the functionality of this lib or it might be completely fine. In any case. You might want to open a new issue to request support for react 17 and perhaps someone can look into the changes and perform the tests with the new version and if everything is fine, a new version with updated dependencies can be released.

**Comment by jayp0521** [comment]
> @jayp0521 Your issue comes from the fact that you are using the next major version of react (i.e. 17.X) and this library is not released for this version yet. There might be breaking changes in vision 17 that impact the functionality of this lib or it might be completely fine. In any case. You might want to open a new issue to request support for react 17 and perhaps someone can look into the changes and perform the tests with the new version and if everything is fine, a new version with updated dependencies can be released.

Yes, I was going to create a PR and test probably this weekend. I was only suggesting a temporary workaround that worked for me if people wanted to be on React 17.

**Comment by matamatanot** [comment]
https://www.npmjs.com/package/react-firebase-hooks/v/3.0.0-alpha.3

**Comment by chrisbianca** [comment]
The full release has now been published: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1

**Comment by Godefroy** [comment]
Great, thanks 🙏
