### ISSUE TITLE
TypeError: v1.isEqual is not a function

### ISSUE THREAD

**Issue by cmmartin** [CSFrequency/react-firebase-hooks#11]
I'm getting `TypeError: v1.isEqual is not a function` when I use the `useDocument` hook

```javascript
const profileRef = firebase
    .firestore()
    .collection('users')
    .doc(user.uid)

const { error, loading, value } = useDocument(profileRef)
```

```
 "react": "16.8.3",
 "react-firebase-hooks": "^1.1.0",
 "react-native": "0.59.1",
 "react-native-firebase": "^5.2.3",
```

Any ideas?

**Comment by dizzyrobin** [comment]
I think it is a problem related to [react-native-firebase](https://github.com/invertase/react-native-firebase), because the `isEqual` function is not implemented in `DocumentReference` as you can see in the [docs](https://rnfirebase.io/docs/v5.x.x/firestore/reference/DocumentReference).

This is the [missing function](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#isequal) in the firebase official documentation.

**Comment by chrisbianca** [comment]
@dizzyrobin You're correct, `DocumentReference` in `react-native-firebase` doesn't implement the `isEqual` method, which is a bit unfortunate.  

@cmmartin It might be worth raising an issue with them directly to see if they can add it either to v5 or their upcoming v6.

In the meantime, I'll have a think to see if this can be worked around in any way.

**Comment by cmmartin** [comment]
Thanks @dizzyrobin and @chrisbianca for helping diagnose the problem. I opened an [issue](https://github.com/invertase/react-native-firebase/issues/2028) in react-native-firebase about this. I'll let you guys know if I find a suitable workaround in the meantime

**Comment by cmmartin** [comment]
This was added to react-native-firebase in [v5.2.4 ](https://github.com/invertase/react-native-firebase/issues/2028)

**Comment by chrisbianca** [comment]
That's great, thanks for the update!

**Comment by DrSkunk** [comment]
For those who came across this error when not using react-native-firebase, I recently received this error when i supplied a string instead of a ref to `useList()`

The following snippet produced the error:
```javascript
  const [snapshots, loading, error] = useList("/leaderboard");
```

it is fixed by replacing it with a ref like so:

```javascript
  const [snapshots, loading, error] = useList(firebase.database().ref("/leaderboard"));
```
