### ISSUE TITLE
Transform method doesn't exist on useCollectionData on latest

### ISSUE THREAD

**Issue by olivertuck** [CSFrequency/react-firebase-hooks#113]
On the documentation it says in the options param for useCollectionData I should be able to provide a transform function. But on the latest version 2.2, TypeScript warns me that it doesn't exist and it doesn't do anything.

Has this definitely been added properly? I really need to use this.

Thanks

**Comment by chrisbianca** [comment]
@olivertuck this has been as part of https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1 which has now been released to NPM
