### ISSUE TITLE
Cannot find module 'react-firebase-hooks' or its corresponding type declarations

### ISSUE THREAD

**Issue by piousdeer** [CSFrequency/react-firebase-hooks#116]
I can't import the module neither in a CRA app nor in an empty TypeScript project. Steps to reproduce:
```sh
mkdir test-react-firebase-hooks
cd test-react-firebase-hooks
npm init -y
npm i -D typescript
npx tsc --init
npm i react-firebase-hooks
echo "import {} from 'react-firebase-hooks'" > index.ts
npx tsc
```

**Comment by osilviotti** [comment]
You shouldn't be importing from the root, it should be one of either `react-firebase-hooks/auth`, `react-firebase-hooks/firestore`, `react-firebase-hooks/storage`, or `react-firebase-hooks/database`.

**Comment by chrisbianca** [comment]
@osilviotti is correct, in order to minimise application bundle size, you should import from the packages that you're interested in using.
