### ISSUE TITLE
UseCollectionData wrong type (TS2345)

### ISSUE THREAD

**Issue by app-akrobaten** [CSFrequency/react-firebase-hooks#120]
Hello, now with the new version i get the following error - in V2.2.0 it works:

TS2345: Argument of type 'DocumentReference<DocumentData>' is not assignable to parameter of type 'Query<FirebaseCourse>'.   Type 'DocumentReference<DocumentData>' is missing the following properties from type 'Query<FirebaseCourse>': where, orderBy, limit, limitToLast, and 4 more.

code: 
``` 
const [coursesData] = useCollectionData<FirebaseCourseWithUid>(
    firebase.firestore().collection('courses'),
    { idField: 'uid' }
  );
```

FirebaseCourseWithUid:
```
export type FirebaseCourseWithUid = {
  title: string;
  description: string;
  start: string;
  duration: number;
  recurrence: { daysOfWeek: Array<number>; weekInterval: number } | null;
  trainerId: string;
  imageUrl: string;
  isOnline: boolean;
  uid: string;
};
```

**Comment by dangreaves** [comment]
I'm having the same issue since upgrading to v3. Here's a simple example.

```ts
interface Task {
  title: string,
  message: string
}

const [tasks, loading, error] = useCollectionData<Task>(
  firebase
    .firestore()
    .collection("tasks")
);
```

This throws the following type error.

```
Argument of type 'CollectionReference<DocumentData>' is not assignable to parameter of type 'Query<Task>'.
  The types returned by 'where(...)' are incompatible between these types.
    Type 'Query<DocumentData>' is not assignable to type 'Query<Task>'.
      Type 'DocumentData' is missing the following properties from type 'Task': title, message
```

It seems that removing the generic from `firebase.firestore.Query` does the trick, but I'm not sure what type features this then loses. I'm guessing that generic perhaps adds types into the `where()` method, but unsure.

https://github.com/CSFrequency/react-firebase-hooks/blob/master/firestore/useCollection.ts#L34

```diff ts
export const useCollectionData = <
  T = firebase.firestore.DocumentData,
  IDField extends string = '',
  RefField extends string = ''
>(
-  query?: firebase.firestore.Query<T> | null,
+  query?: firebase.firestore.Query | null,
  options?: DataOptions<T>
): CollectionDataHook<T, IDField, RefField> => {
  return useCollectionDataInternal(true, query, options);
};
```

**Comment by chrisbianca** [comment]
I've just been having a play with this and there's definitely some underlying issues with how the typings were previously assigned. I've cleaned this up as per @dangreaves suggestion which seems to have resolved the issue. I'll get this released as a bug fix now.

**Comment by dangreaves** [comment]
Thanks for addressing that so quickly @chrisbianca, fingers crossed that cracks it. Confirming your question re. `firebase` version, I'm on `firebase@8.2.9`.

**Comment by app-akrobaten** [comment]
Hey. Thank you for your quick reply. Im also on `firebase@8.2.9 `
