### ISSUE TITLE
Feature request. Add hook for calling firebase cloud functions

### ISSUE THREAD

**Issue by samrit** [CSFrequency/react-firebase-hooks#123]
Apologies if this is something already implemented and I missed it. I looked but could not find hooks for cloud functions in firebase.

**Comment by samrit** [comment]
> Can you give an example because I don't think it's a valid request as all the cloud functions are backend stuff, so no hooks there. Then do you want hooks to consume data ( the rest api data ).

Hey! Thanks for the response. So here is an example, I have collections and documents, but I write a function to validate some custom business logic and return some value and expose that as a callable https function.  I can now call this function using the firebase SDK.  It would be useful to have hooks to be able to call these functions. Something like,

```
const [functionCall, response, executing, error] = useFunction("myAwesomeCustomFunction")

// and then you could use it in some handler
const handleClick = (args) => {
  functionCall(args);
}
 
```

And then the UI could react to whatever the values of `error`, `response`, and `executing` end up being

**Comment by samrit** [comment]
Feel free to close if you feel this is outside the scope. Thanks for considering.

**Comment by lorstenoplo** [comment]
> Feel free to close if you feel this is outside the scope. Thanks for considering.

No nothing like that, I just couldn't think of a use case.
I have not worked with cloud functions ( just wanted to inform )

**Comment by diginikkari** [comment]
I would also like to see support for firebase function calls. There are callable functions, which are very nice to use with firebase ([documentation](https://firebase.google.com/docs/functions/callable#web)). Callable functions integrate nicely with firebase authentication and are IMO easy to use.

**Comment by chrisbianca** [comment]
@samrit thanks for the suggestion, this would be a great addition to the library. I will try and take a look at this over the next few weeks, but obviously welcome any PRs in the meantime

**Comment by chrisbianca** [comment]
This has been added and will be part of the upcoming v5 release in the next week or two

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0
