### ISSUE TITLE
useDocumentData returns null, false, null if document does not exists

### ISSUE THREAD

**Issue by otusweb** [CSFrequency/react-firebase-hooks#124]
I'm new to using this library so feel free to point me in the right direction if I missed anything obvious.

When using the following code with userToDisplayUID which does indeed have a document in the database everything works as expected. The problem is that if there is no document with this ID, I simply end up with userToDisplay = null, userToDisplayLoading = false, userToDisplayError = null
```
    const userToDisplayQuery = FirebaseApp.firestore()
      .collection(CollectionNames.publicUserProfiles)
      .doc(userToDisplayUID);
const [userToDisplay, userToDisplayLoading, userToDisplayError] = useDocumentData<PublicUserProfile>(
      userToDisplayQuery,
    );
```

Is the right approach to assume that if there is no error, loading is done and the object is null that means it does not exists?

**Comment by chrisbianca** [comment]
@otusweb that's correct. Firestore does not return any form of error to indicate that the document doesn't exist. There is a `.exists` field on the underlying document snapshot, but as you're using the `Data` method, then we simply map this to a null response. If you think this should behave differently, then I'm very open to suggestions to consider.

In the meantime, I'm going to close this as it's not an issue per se
