### ISSUE TITLE
Cannot Build Project With Vite

### ISSUE THREAD

**Issue by graytonio** [CSFrequency/react-firebase-hooks#127]
I am trying to build my project with vite after developing it and it is throwing the following error.

```
node_modules/react-firebase-hooks/auth/dist/auth/types.d.ts:2:50 - error TS2304: Cannot find name 'AuthActionHook'.
2 export declare type EmailAndPasswordActionHook = AuthActionHook<firebase.auth.UserCredential, firebase.FirebaseError>;
```

The library was working in development mode but failed to build properly.

**Comment by chrisbianca** [comment]
This seems like it's going to be an issue with Vite rather than with the library given that there haven't been any other reports of issues with the new releases.

Vite is not something that I am familiar with so I don't think I'll be able to help you get to the bottom of this one.

**Comment by mfilteau** [comment]
tsc is used as part of vite's build and the package seems to be missing some types.

"build": "tsc & vite build"

I think exporting AuthActionHook & IDOptions should fix the issue.

**Comment by chrisbianca** [comment]
This has now been resolved in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.4
