### ISSUE TITLE
Support withConverter

### ISSUE THREAD

**Issue by berdyshev** [CSFrequency/react-firebase-hooks#128]
Firestore supports converting data to an instance of any type using FirestoreDataConverter. So doc here https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter

But as I can see now [`snapshotToData`](https://github.com/CSFrequency/react-firebase-hooks/blob/16d1f2edb7b276d1ff565ec5c6ac324d1e602324/firestore/helpers/index.ts#L14-20) spreads the data into an object and this will throw away the prototype of the data.

BTW, I think that the implementation of `transform` repeat the same functionality but in a bit more limited way — it doesn't provide access to DocumentSnapshot instance.

**Comment by berdyshev** [comment]
@chrisbianca sorry, is it possible to release this fix, because this is required for our project?

**Comment by chrisbianca** [comment]
@berdyshev this has now been released as part of https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.3, sorry for the delay
