### ISSUE TITLE
New hook for file upload into storage

### ISSUE THREAD

**Issue by dohomi** [CSFrequency/react-firebase-hooks#133]
Hi
as I use some parts of this hook I missed a file upload hook. Here is my version of it - if this is useful I am happy to do a PR or just grab the code and adjust it.
```ts
import { useMemo, useState } from 'react'
import firebase from 'firebase/app'
import 'firebase/storage'

const uploadFile = async ({ blobUrl, name }) => {
  if (!blobUrl || !name) return null

  const blob = await fetch(blobUrl).then((r) => r.blob())
  const snapshot = await firebase.storage().ref().child(name).put(blob)
  return snapshot.ref.getDownloadURL()
}

const useUploadFiles = (): [
  (files: File[], filePrefix?: string) => Promise<void>,
  {
    error: firebase.FirebaseError
    loading: boolean
    files: string[] | undefined
  }
] => {
  const [error, setError] = useState<firebase.FirebaseError>()
  const [files, setFiles] = useState<string[] | undefined>()
  const [loading, setLoading] = useState<boolean>(false)
  const uploadFiles = async (filesToUpload: File[], filePrefix?: string) => {
    setLoading(true)
    try {
      const downloadUrls: Promise<string>[] = []
      Array.from(filesToUpload).forEach((file) => {
        downloadUrls.push(
          uploadFile({
            blobUrl: URL.createObjectURL(file),
            name: `${filePrefix || ''}${file.name}`
          })
        )
      })
      const allFiles = await Promise.all(downloadUrls)
      setFiles(allFiles)
    } catch (e) {
      setError(e)
    }
    setLoading(false)
  }
  const memoized = useMemo(() => {
    return { files, error, loading }
  }, [files, error, loading])
  return [uploadFiles, memoized]
}
export default useUploadFiles
```

**Comment by dohomi** [comment]
I came up with a slightly optimized version: https://gist.github.com/dohomi/78d240028a3450c5477e91e6004288ab

**Comment by lud-hu** [comment]
Works like a charm! Thanks!
I vote for adding it to the lib. 👍

**Comment by chrisbianca** [comment]
Thanks @dohomi, this would be a good addition. Feel free to submit a PR for review, or let me know and I can take your code and apply myself.

**Comment by dohomi** [comment]
@chrisbianca feel free to grab https://gist.github.com/dohomi/78d240028a3450c5477e91e6004288ab#file-useuploadfiles-ts which you can drop in and only need to make small modifications for the loading and error handling. The payload is:
```ts
type UploadFilePayload = {
  path: string
  name: string
  type: string
  size: number
}
```
I am using this right now and found it most flexible. I am saving this 4 params inside of my database and on request I use the useDownloadURL hook to receive its name.

**Comment by chrisbianca** [comment]
I have finally got round to implementing a `useUploadFile` hook which will be released as part of v5.

@dohomi thanks for the inspiration - whilst I haven't taken yours in its entirety, I leaned on it heavily whilst implementing the version included with v5.

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0
