### ISSUE TITLE
`IDOptions` is not included in exported types

### ISSUE THREAD

**Issue by Snailed** [CSFrequency/react-firebase-hooks#134]
When I try to use the firestore hooks, `tsc` will throw the following error:
```
> eslint '*/**/*.{js,ts,tsx}' && npx tsc --out /dev/null

node_modules/react-firebase-hooks/firestore/dist/firestore/types.d.ts:6:48 - error TS2304: Cannot find name 'IDOptions'.

6 export declare type DataOptions<T> = Options & IDOptions<T>;
                                                 ~~~~~~~~~

node_modules/react-firebase-hooks/firestore/dist/firestore/types.d.ts:10:56 - error TS2304: Cannot find name 'IDOptions'.

10 export declare type OnceDataOptions<T> = OnceOptions & IDOptions<T>;
```

This makes my CI/CD workflow fail.
To fix it, the `IDOptions` type should be exported.

**Comment by mfilteau** [comment]
I got the IDOption type and this also:

node_modules/react-firebase-hooks/auth/dist/auth/types.d.ts:6:50 - error TS2304: Cannot find name 'AuthActionHook'.

6 export declare type EmailAndPasswordActionHook = AuthActionHook<firebase.auth.UserCredential, firebase.FirebaseError>;

**Comment by chrisbianca** [comment]
This has now been resolved in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.4
