### ISSUE TITLE
Examples for how to use the hooks

### ISSUE THREAD

**Issue by marduzca** [CSFrequency/react-firebase-hooks#140]
Hi there!
I have already spent a good amount of time searching for examples to help me understand how to use these hooks, but sadly with no success.
Are there any examples that you provide to help people understand the basics and make clear what each hook does? It would really come in handy for an amateur in firebase that doesn't understand the basic concepts yet, like me.
Thank you!

**Comment by lorstenoplo** [comment]
Hello!
Firstly I recommend you to get to know and work with firebase for atleast 2 projects
At this point of time you will know almost all potential errors and how to fix them ( ofcourse basics ). 
After that try converting your existing react firebase projects to the one that uses hooks.

And for resources I have some :
For basic firebase stuff : 
1. https://youtu.be/RDV3Z1KCBvo
2. https://youtu.be/HF65cySUYao
3. https://youtu.be/f7T48W0cwXM
4. https://youtube.com/user/ssangha32

For react-fireabse hooks : 
https://youtu.be/zQyrwxMPm88

**Comment by marduzca** [comment]
I will do it that way then, thank you!

Anyways, some examples using the hooks would be great even for people that have some experience with firebase already
