### ISSUE TITLE
Unable to import util/ functions from node_modules

### ISSUE THREAD

**Issue by gavingolden** [CSFrequency/react-firebase-hooks#142]
### Version:
3.0.2

### Background:
I'm unable to import the `useIsEqualRef` and other similar utility functions. I want to use them for my own custom hook.

I'm using typescript and Expo (react-native) and I tried a variety of import combinations but I always get this error. I'm not sure if this is a typescript issue or and underlying node module issue (I know nearly nothing about module resolution).

The typescript compiler seems happy but it fails when I run `expo start` (which builds everything).
```ts
import { useIsEqualRef, useLoadingValue } from 'react-firebase-hooks/firestore/dist/util';
```
```
Unable to resolve module react-firebase-hooks/firestore/dist/util from /Users/me/code/convo/mobileApp/hooks/myFile.ts: 
react-firebase-hooks/firestore/dist/util could not be found within the project or in these directories:
  node_modules/react-firebase-hooks/firestore/dist
```

The node module seems to be exporting them from `/firestore/dist/util/index.d.ts`, but I'm not sure if that aligns with the actual underlying js code -- I don't know how all of that works.

### Request:
* Are these supposed to be importable?
* If not, can the utility functions be exposed as their own submodule?

**Comment by chrisbianca** [comment]
@gavingolden these utility methods were never intended to be importable outside of the `react-firebase-hooks` package as I hadn't perceived a use for them.

There is however no real reason why they couldn't be if they are useful for developers, so I will take a look.

**Comment by chrisbianca** [comment]
@gavingolden I realise this has been a long time coming, but this will be added in the upcoming v5 release

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0

**Comment by gavingolden** [comment]
awesome, thanks for making the change
