### ISSUE TITLE
Order firestore documents by timestamp using useCollectionData

### ISSUE THREAD

**Issue by zip27** [CSFrequency/react-firebase-hooks#145]
**Version**
3.0.3

**Problem**
I am trying to order documents from Firebase Cloud Firestore based on a timestamp. On each document within the Firestore collection, I have a "createdAt" field followed by a timestamp. I am also using useCollectionData hook to display data from this document in this format:
`const [docs] = useCollectionData(docRef, { idField: "id" })` where `docRef` refers to a collection. How can I implement ordering based on timestamp?

I want to use the functionality outlined in this part of the [Firebase Docs](https://firebase.google.com/docs/firestore/query-data/order-limit-data) and [here](https://maye.pwafire.org/articles/using-timestamp-to-filter-and-order-firebase-cloud-firestore-documents/). However, I can't find a way to do this in useCollection or any other hook.

**Request**
How can I use `useCollectionData` hook to order Firestore documents based on timestamp?

**Comment by chrisbianca** [comment]
@zip27 You can simply pass a ref that has ordering applied to `useCollectionData`:

```
const docRef = firebase.firestore().collection("devs").orderBy("createdAt", "desc");
const [docs] = useCollectionData(docRef, { idField: "id" });
```
