### ISSUE TITLE
Feature request. Add hook for calling `sendPasswordResetEmail`

### ISSUE THREAD

**Issue by Andrew-web-coder** [CSFrequency/react-firebase-hooks#146]
Hi,

It would be nice to have a wrapper with loading/error state for `auth.sendPasswordResetEmail(email)`. Thanks.

**Comment by chrisbianca** [comment]
This has just been done here https://github.com/CSFrequency/react-firebase-hooks/commit/08489c5de26b366669149fc98df449527fe59df6 and will be released in the upcoming v5 in the next week or two

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0
