### ISSUE TITLE
Mock `useDocumentDataOnce` with jest

### ISSUE THREAD

**Issue by RobertBrunhage** [CSFrequency/react-firebase-hooks#148]
I am using `useDocumentDataOnce` and trying to mock out the result but not being successful.

My understanding is that the first one is the data, second one is loading and the last one is the error, but this just makes the code get stuck in the test.

```
jest.mock("react-firebase-hooks/firestore", () => ({
  useDocumentDataOnce: () => [
    {
      name: test,
    },
    false, 
    null,
  ],
}));
```

**Comment by imjared** [comment]
This link helped me out: https://stackoverflow.com/a/66091532/628699

**Comment by chrisbianca** [comment]
Closing as the linked stackoverflow answers this question
