### ISSUE TITLE
Do I need to unsubscribe listeners?

### ISSUE THREAD

**Issue by ripern** [CSFrequency/react-firebase-hooks#151]
I'm using useDocumentData (among others) and I was wondering if I need to unsubscribe listeners myself. I tried to figure out if it was being done automatically by looking at https://github.com/CSFrequency/react-firebase-hooks/blob/1d1ca28241ece8f4662aa2aeadff132cd880c32b/firestore/useDocument.ts#L96 but couldn't really find. Please explain and pointing to the source would be greatly appreciated! I just noticed useMemo is used internally, that's nice!

Thanks for a very useful library!

**Comment by ishowta** [comment]
https://github.com/CSFrequency/react-firebase-hooks/blob/1d1ca28241ece8f4662aa2aeadff132cd880c32b/firestore/useDocument.ts#L77-L79
It should not be necessary since it will be unsubscribed here.
