### ISSUE TITLE
Package `main` field points to non-existing index file in `dist`

### ISSUE THREAD

**Issue by byCedric** [CSFrequency/react-firebase-hooks#154]
Hi! I'm Cedric and I work on [Snack](https://snack.expo.io) - a tool for React Native snippets. 

We received a report about this package causing bundling errors and it's related to the `main` field in the `package.json` pointing to a non-existing `dist/index.*.js` file. Here is a [more in-depth explanation of what's happening](https://github.com/expo/snack/issues/134#issuecomment-852291059). 

Not sure if others are running into this as well, but thought I'd mention it.

**Comment by Temperantia** [comment]
Had the same problem, you need to import the specific module instead of the generic package as stated in the mentioned issue above.
In my case `import { useCollection } from "react-firebase-hooks/firestore";` solved the issue

**Comment by chrisbianca** [comment]
Closing this issue as it sounds like they were importing from the main library rather than the sub package as required
