### ISSUE TITLE
How to run two dependent firestore queries using hooks?

### ISSUE THREAD

**Issue by stijnvanlieshout** [CSFrequency/react-firebase-hooks#155]
I just installed this package and am trying to rewrite the following:

```
const [team, setTeam] = React.useState(null);
const [teamOwner, setTeamOwner] = React.useState(null);

React.useEffect(() => {
  const unsubscribe = firebase.team(match.teamId)
    .onSnapshot((snapshot) => {
      setTeam(snapshot().data());
    });
  return () => unsubscribe();
}, [firebase, match.teamId]);

**// I can only start start fetching `teamOwner` once `team` is known**

const teamOwnerId = team ? team.ownerId : null;
React.useEffect(() => {
  if (teamOwnerId) {
    firebase.teamOwner(teamOwnerId)
      .get()
      .then((doc) => {
        setTeamOwner(doc.data());
      });
  }
}, [firebase, teamOwnerId]);

```

My code using this package looks like this:
```
const [team, loadingTeam] = useDocumentData(firestore.doc(`teams/${match.teamId}`))
const [teamOwner, loadingTeamOwner] = useDocumentDataOnce(team ? firestore.doc(`teamOwners/${team.ownerId}`) : null);
```

Question 1:
As you can see, the ref argument for the second `useDocumentDataOnce` call (for teamOwner) is null until team has loaded. This works fine, but I wonder if it is ok to chain these hooks like this? Do I perhaps make unnecessary firestore calls this way?

Question 2:
Currently, my loading indicator flickers because `loadingTeamOwner` is `false` initially and only turns true as soon a `team` exists. Would it be possible to initiate `loadingTeamOwner` to `true` (I could not find that in the docs)?

I am looking for an `initLoading` option that I could use like this:
```
const [team, loadingTeam] = useDocumentData(
   firestore.doc(`teams/${match.teamId}`), {initLoading: true }
)
const [teamOwner, loadingTeamOwner] = useDocumentDataOnce(
   team ? firestore.doc(`teamOwners/${team.ownerId}`) : null, {initLoading: loadingTeam }
);
```

**Comment by vuza** [comment]
I've had the same problem, this helped: https://stackoverflow.com/questions/65867856/infinite-loop-when-working-with-react-and-react-firebase-hooks

Hope it helps you too! :)

**Comment by chrisbianca** [comment]
@stijnvanlieshout Apologies for the delay, in response to your questions:

1) Yes, chaining hooks like this is the recommended way to work with dependencies, and the reason that the hooks support a `null` reference
2) Unfortunately this isn't something which is supported, and would be a bit fiddly to get working correctly and intuitively. I would suggest that you simply chain the two `loading` flags together so that if one of them is true then you display the loading indicator.

I hope that helps.
