### ISSUE TITLE
Data Type definition

### ISSUE THREAD

**Issue by bartkoedijk** [CSFrequency/react-firebase-hooks#158]
Hi,

I have been using your NPM package for a while now and I love it.
Currently I am using Typescript + React Native for my project.

I came across a Type definition and wondert if was necessary.

`const [values, loading, error] = useCollectionData<MyType[]>(ref);`

In the line above I would expect values to be a type of: **MyType[]**.
Instead it returned: values: `Data<MyType[], "", "">[] | undefined`

Is it a possibility to remove the wrapper?

Thank you,
Bart

**Comment by hannojg** [comment]
Hi @bartkoedijk,

I am currently porting this library over for react-native. I explicitly fixed the problem you are describing in this new library.
https://github.com/skillnation/react-native-firebase-hooks

The library is stable now, however it is currently missing documentation, but the API works 1:1 the same as with this library.

**Comment by chaosLegacy** [comment]
Hi,
I'm new to firebase, and I found these hooks pretty much useful, but I have a little problem.

I'm using firebase ^9.6.1 along with react-firebase-hooks 4.0.1

This is the piece of code that I use to retreive my messages from firestore
The type Post that i' passing to useCollectionData seems generating an error: see below

```
    const messagesRef = collection(firestore, 'messages');
    const q = query(messagesRef, orderBy('createdAt'), limit(25));

    const [messages] = useCollectionData<Post[]>(q, { idField: 'id' });
```


```
Argument of type 'Query<DocumentData>' is not assignable to parameter of type 'Query<Post[]>'.
  Types of property 'converter' are incompatible.
    Type 'FirestoreDataConverter<DocumentData> | null' is not assignable to type 'FirestoreDataConverter<Post[]> | null'.
      Type 'FirestoreDataConverter<DocumentData>' is not assignable to type 'FirestoreDataConverter<Post[]>'.
        The types returned by 'fromFirestore(...)' are incompatible between these types.
          Type 'DocumentData' is not assignable to type 'Post[]'
```

Has anyone faced a similar issue?

**Comment by 0x80** [comment]
When I started using this library I think it didn't have generics yet, but I also wanted to have a different type of response. In my code I like to pass around documents as `{id: string, data: T, ref: DocumentReference}`, and also I didn't see the benefit of having an error returned everywhere. I preferred to have it just throw, as query errors should be very rare anyway (like missing indexes)

So I wrote some basic wrappers that call the hooks without using types, and then type the response of the wrapper.

Here's an example

```ts
export function useTypedDocument<T>(
  ref: firebase.firestore.DocumentReference,
): [Document<T> | undefined, boolean] {
  const [snapshot, isLoading, error] = useDocument(ref);

  if (error) {
    throw error;
  }

  const doc = snapshot?.exists
    ? { id: snapshot.id, data: snapshot.data() as T, ref: snapshot.ref }
    : undefined;

  return [doc, isLoading];
}
```

You could do the same for useCollection or other hooks.

Even if you want to keep the response the same, you could wrap the hook 1:1 and apply the types you think it should have. Then later remove your wrapper (find/replace) when the library is fixed.

**Comment by philldev** [comment]
removing generics <T> from DocumentReference in useDocument.d.ts seems to solve the problem for me.

- before
`export declare const useDocumentData: <T = DocumentData, IDField extends string = "", RefField extends string = "">(docRef?: DocumentReference| null | undefined, options?: DataOptions<T> | undefined) => [Data<T, IDField, RefField> | undefined, boolean, FirestoreError | undefined];`

- after
`export declare const useDocumentData: <T = DocumentData, IDField extends string = "", RefField extends string = "">(docRef?: DocumentReference| null | undefined, options?: DataOptions<T> | undefined) => [Data<T, IDField, RefField> | undefined, boolean, FirestoreError | undefined];`

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0

**Comment by shamoons** [comment]
Does this have type support?
