### ISSUE TITLE
feature request for: namedQuery

### ISSUE THREAD

**Issue by Yoruba** [CSFrequency/react-firebase-hooks#167]
Is it possible to use firestore.namedQuery('cached-query') with react-firebase-hooks?
If not, it would be nice to have.

[https://firebase.google.com/docs/firestore/bundles](url)

```
  const query = await db.namedQuery('latest-stories-query');
  const storiesSnap = await query.get({ source: 'cache' });
```

Thanks, Yoruba

**Comment by chrisbianca** [comment]
@Yoruba I've just been (belatedly) looking into this, and named queries are already supported by the `useCollection` and `useCollectionData`:

```
const query = await db.namedQuery('latest-stories-query');
const [value, loading, error] = useCollection(query);
```
