### ISSUE TITLE
Firestore Hooks: Trigger a refetch manually?

### ISSUE THREAD

**Issue by arbejd** [CSFrequency/react-firebase-hooks#170]
Hi folks, thanks for a nice module!

Is there a way trigger a manual refetch? I have a use case where a claim in firestore may be set after mounting, so the hook could use a refetch under certain conditions.

Thank you!

**Comment by theZaX** [comment]
https://github.com/CSFrequency/react-firebase-hooks/issues/53 

I think it's a pretty important use case but it doesn't look like it'll be added to this module. This module also doesn't support custom claims so I'll probably stop using it. 

I've been using the source code of the hooks to make my own with custom functionality. It should be pretty easy to just also return the get function from the existing usedocumentdataonce hook.

**Comment by ZakKa89** [comment]
Seconded. I'm in a project where suddenly the need for this arised. The real-time functionality that comes with useCollectionData was being perceived as unwanted by the users, so I'd like to manually refetch. Quite a bummer that there is no way to do this.

**Comment by chrisbianca** [comment]
This functionality has just been added and will be released as part of the upcoming v5. Apologies for the delay, but this was a fairly fundamental change that required some thought and time.

Reference: https://github.com/CSFrequency/react-firebase-hooks/commit/0c7036875214c772280e1663f6aa4a35a31c4625

**Comment by arbejd** [comment]
Thank you @chrisbianca , i will take it for a spin asap

**Comment by chrisbianca** [comment]
v5 is now released: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v5.0.0

**Comment by ZakKa89** [comment]
Maybe I'm missing how to use this? Because it doesn't seem to be a function, I can't call this 'reload'.

**Comment by ZakKa89** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/24491661/233214609-ab156dfd-eb8a-4e6f-b15b-e7ddb33c80af.png">

Ah I found the issue, it's the 5th item not the 4th that triggers the reload
