### ISSUE TITLE
Question about optimization and performance using useAuthState

### ISSUE THREAD

**Issue by 1alexvash** [CSFrequency/react-firebase-hooks#171]
If I have a page1 that uses **useAuthState** hook, and then user jumps to page2 which also uses this hook.
Is it good from a performance standpoint?

Or it is better to call this hook once, and store this information in Context/Redux?

```js
const [user, loading, error] = useAuthState(auth);
```

**Comment by vb5ono** [comment]
Definitely the second option, you should call it once. I usually use the React Context but I guess you could use Redux too.
Though I don't think your question should be considered as an issue !

Have a good one !

**Comment by jamesjara** [comment]
@vb5ono could you elaborate on the reason  why it's better

**Comment by chrisbianca** [comment]
Actually, the hook uses `auth.currentUser` as the default value when it loads, so there will be no additional network request so there is no difference between `useAuthState` and using the context or redux.
