### ISSUE TITLE
Elegant way to combine useListKeys and useObject

### ISSUE THREAD

**Issue by matthieunelmes** [CSFrequency/react-firebase-hooks#175]
So I have a list of keys that I can obtain with the database useListKeys hook.

I then want to iterate through the keys to return each relevant object. Any help would be much appreciated.

**Comment by chrisbianca** [comment]
@matthieunelmes apologies for the delayed response. I would suggest you have two components, one loading the list of keys using `useListKeys` and the rendering a list of child components which uses `useObject`
