### ISSUE TITLE
v4 does not work with react-native

### ISSUE THREAD

**Issue by Yonom** [CSFrequency/react-firebase-hooks#181]
The README.md advertises React Native Firebase support:

> React Firebase Hooks works with both the Firebase JS SDK and React Native Firebase, although some of the typings may be incorrect.

but v4 does not work with react-native-firebase v13.0.1:

![image](https://user-images.githubusercontent.com/1394504/140596388-cf04bbfe-6ae3-452d-9ab9-6f0074726539.png)

**Comment by chrisbianca** [comment]
@Yonom thanks for flagging. Unfortunately, it seems that with v9 of firebase, the types of the web and react native versions have diverged too far to easily support both. I will remove the note for the time being and consider if there is a better way to support RN in the future

**Comment by hannojg** [comment]
@chrisbianca I'd like to create a library especially for react-native. Are you fine with me basically copying the code of version 3? I'd highlight that the implementation is based on this library. I am asking because I am not entirely sure how apache 2.0 works.

**Comment by Yonom** [comment]
@hannojg looking forward to it!

**Comment by hannojg** [comment]
@Yonom its already done: https://github.com/skillnation/react-native-firebase-hooks
The api is the same (except for the imports ofc). Just haven't had the time yet to put up a proper documentation/readme

**Comment by penx** [comment]
I created a wrapper that can be used with any async function, including Firebase functions, that mirrors GraphQL's useQuery and useLazyQuery hook. This is what we're using to turn our react-native Firebase queries in to hooks.

Hopefully it's of use to others!

https://github.com/penx/use-async-query
