### ISSUE TITLE
Attempted import error: 'firebase/app' does not contain a default export (imported as 'firebase').

### ISSUE THREAD

**Issue by Sptele** [CSFrequency/react-firebase-hooks#182]
I am trying to get react-firebase-hooks to work with firebase v9, but I have found an issue that I can't seem to fix. When I run my react project, I get this error: 
`./node_modules/firebase-react-hooks/auth/index.js
Attempted import error: 'firebase/app' does not contain a default export (imported as 'firebase').`

Here is my firebase configuration (v9): [https://paste.myst.rs/6lr0a9op](https://paste.myst.rs/6lr0a9op)

How can I resolve this?
I am using firebase@9.4.1 and react-firebase-hooks@4.0.1

**Comment by chrisbianca** [comment]
@Sptele it looks like you're using `firebase-react-hooks` rather than `react-firebase-hooks`
