### ISSUE TITLE
Issue with "useDocument"

### ISSUE THREAD

**Issue by T4533N** [CSFrequency/react-firebase-hooks#184]
I don't know what I am doing wrong but according to docs, passing the docRef isn't working! 

![image](https://user-images.githubusercontent.com/44163644/142643136-b6d9ebe2-feea-4546-be3b-39d0f50980c3.png)

**Comment by chrisbianca** [comment]
@T4533N apologies for the slow reply. It looks like you're trying to use hooks on the server side of a Next.js app which is not supported by Next.js
