### ISSUE TITLE
What's the best practice getting a document without refetch every component rerendering

### ISSUE THREAD

**Issue by idangozlan** [CSFrequency/react-firebase-hooks#187]
Hi,

There's something not clear to me about the `useDocument`, which either of the examples is not touching, and this is the fetching every time the component is getting rerendered.

Says we have a component with counter and "increase counter" button, every time we'll click on the increase button, it will fetch again the document.
Is there anything to do about that?

Thanks.

**Comment by idangozlan** [comment]
Nvm, I didn't notice that there's an internal cache layer.

**Comment by molimauro** [comment]
Sorry, where did you find this internal layer? It just uses the default Firestore approach to this. You have to manually specify the option `cache` to check the cache first instead of going directly to the server. Or am I missing something? :)

**Comment by glaucoheitor** [comment]
@idangozlan can you elaborate a little bit about this internal cache layer?

**Comment by idangozlan** [comment]
I assume that the way Firebase SDK works is that when you trigger a change to the doc, it will not be refecthed from the same instance that triggered the change, so it will not have any kind of an infinite loop.
Again, this is my guess, based on the network traffic and common sense.
