### ISSUE TITLE
Why clean up returns undefined?

### ISSUE THREAD

**Issue by 1alexvash** [CSFrequency/react-firebase-hooks#189]
```js
const [collectionData] = useCollectionData(query, {
    idField: "id",
  });

  React.useEffect(() => {
    return () => {
      console.log("collectionData:", collectionData);
    };
  }, []);
```

![image](https://user-images.githubusercontent.com/46556479/146232705-35bdeaf5-8b60-46a9-b4db-ff5de1747f98.png)

**Comment by chrisbianca** [comment]
@1alexvash I'm not entirely sure what you're hoping to achieve with this code snippet, but the `useEffect` will only ever evaluate once on the initial render as you are passing an empty array `[]` into the second field. This means that when the collection data is actually loaded it won't re-trigger.

This isn't an issue with the library so I'm going to close

**Comment by 1alexvash** [comment]
I need to send a request to the server to mark notifications as **seen** when the component unmounts

I have achieved it using two refs and useEffect, but I'm not sure if it the best practice

  const notificationsUnseen = React.useRef<NotificationItemType[] | null>(null);
```js
  React.useEffect(() => {
    if (notificationsList) {
      notificationsUnseen.current = notificationsList.filter(
        ({ seen }) => seen === false
      );
    }
  }, [notificationsList]);

  React.useEffect(() => {
    return () => {
      const { current } = notificationsUnseen;

      if (current && current.length > 0) {
        current.forEach(({ id }) => markNotificationSeen(id!));
      }
    };
  }, []);
```
