### ISSUE TITLE
User login status not persisted

### ISSUE THREAD

**Issue by geraldosalazar16** [CSFrequency/react-firebase-hooks#193]
Recently updated my firebase version from "firebase": "^8.3.1" to "firebase": "^9.6.0. Therefore, also upgraded react-firebase-hooks to "^4.0.1" but now it shows this warning

AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage

Also, even if the user successfully login, when the app is closed and reopened, the user has to login again. Seems like the login status/token/information is not been stored

My dependencies

"dependencies": {
    "@expo-google-fonts/poppins": "^0.1.0",
    "@expo-google-fonts/roboto": "^0.2.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/material-bottom-tabs": "^5.3.13",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@types/firebase": "^3.2.1",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/styled-components": "^5.1.7",
    "algoliasearch": "^4.8.6",
    "axios": "^0.21.1",
    "expo": "^43.0.4",
    "expo-app-loading": "~1.2.1",
    "expo-application": "~4.0.0",
    "expo-auth-session": "~3.4.2",
    "expo-cli": "^4.13.0",
    "expo-font": "~10.0.3",
    "expo-google-app-auth": "~9.0.0",
    "expo-google-sign-in": "~10.0.3",
    "expo-linear-gradient": "~10.0.3",
    "expo-random": "~12.0.1",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "firebase": "^9.6.0",
    "global": "^4.4.0",
    "lottie-react-native": "4.0.3",
    "moment": "^2.29.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-firebase-hooks": "^4.0.1",
    "react-instantsearch": "^6.10.3",
    "react-instantsearch-native": "^6.10.3",
    "react-native": "0.64.3",
    "react-native-app-auth": "^6.2.0",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-dotenv": "^2.5.5",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-htmlview": "^0.16.0",
    "react-native-paper": "^4.7.1",
    "react-native-popover-view": "^4.1.0",
    "react-native-popup-menu": "^0.15.11",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-skeleton-content": "^1.0.22",
    "react-native-svg": "12.1.1",
    "react-native-toast-message": "^1.4.9",
    "react-native-vector-icons": "^8.0.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0",
    "styled-components": "^5.2.1"
  }

OS information 
macOS Monterey 12.0.1
MackBook Air (Chip M1)

**Comment by chrisbianca** [comment]
@geraldosalazar16 this is an issue with the underlying Firebase library rather than `react-firebase-hooks`, I would suggest you report an issue with Firebase.
