### ISSUE TITLE
writing data to firestore

### ISSUE THREAD

**Issue by vinodhum** [CSFrequency/react-firebase-hooks#198]
Hi I am new to firebase, I was able to make retrieve data using react-firebase-hooks but cannot find any documentation on how to set, add or push (write) to documents or collections or how to get `ref ` from hooks ?

**Comment by chrisbianca** [comment]
@vinodhum the majority of the hooks in the library are about reading data. There is an open feature request for hooks to support mutating data https://github.com/CSFrequency/react-firebase-hooks/issues/36, but its not something that is actively being worked on at the moment.
