### ISSUE TITLE
[Firestore]  When both useCollectionData and useDocumentData are called for the same collection at first loading, only one result of useCollectionData is returned.

### ISSUE THREAD

**Issue by locona** [CSFrequency/react-firebase-hooks#199]
When both useCollectionData and useDocumentData are called for the same collection at first loading, only one result of useCollectionData is returned.

**examples**

**value1 expects two results to be returned. only one result is returned.**

docs
* id_1
* id_2

```
  const [value1, loading1, error1] = useCollectionData(
   collection(getFirestore(), "react-firebase-hooks"),
    {
      snapshotListenOptions: {
        includeMetadataChanges: true,
      },
    }
  )

  const [value2, loading2, error2] = useDocumentData(
    doc(collection(getFirestore(), "react-firebase-hooks"), "id_1"),
    {
      snapshotListenOptions: {
        includeMetadataChanges: true,
      },
    }
  )

```

**Environtment**
* react-firebase-hooks: 4.0.1
* firebase: 9.6.1

**Comment by locona** [comment]
But it works fine with useCollectionData / useDocumentOnce

Only listen does not seem to work. [...]

**Comment by locona** [comment]
I was expecting all the data to be returned when loading=false.

In the current implementation, loading=false is used even when fromCache: true, but
How about making loading=true when fromCache: true?

@chrisbianca

**Comment by chrisbianca** [comment]
@locona this would fundamentally alter the way that the hooks library work. The `loading` flag is there to indicate whether there is data ready to be displayed, not to indicate the type of data, i.e. whether it is from the cache or not.

A better option would be to have the `xxxData` hooks return the snapshot as well as the data so that the metadata would also be available.

**Comment by locona** [comment]
@chrisbianca 
Thank you!

As for the changes to xxxData, the changes will be large.
I'm going to useCollection to use metadata only for my project and make a decision.
