### ISSUE TITLE
Add `recursive` option

### ISSUE THREAD

**Issue by fvanwijk** [CSFrequency/react-firebase-hooks#202]
Suppose you have a document where one of its fields is reference. When you fetch with `useDocumentData` the reference is not fetched.

For example a BlogPost document:
```
{
  id: 'abc123',
  title: 'My blog',
  author: '/authors/def456'
}
```

```
const [data, loading, error] = useDocument(blogQuery);

console.log(data);
/*
{
  id: 'abc123',
  title: 'My blog',
  author: DocumentReference // I expect this to be resolved into the author data
}
*/
```
`loading` should be false as long as blog and author are not resolved yet.

**Comment by chrisbianca** [comment]
@fvanwijk this is incredibly difficult to implement as it would involve needing to inspect all of the data coming out of Firestore and start requesting any DocumentReference contained there. It would also be highly inefficient as you would only be able to request the data sequentially, so wouldn't scale to the Collection hooks.

With the upcoming v5 functionality, we are moving away from a bespoke internal `snapshotToData` to the built in `FirestoreDataConverter` functionality available within the Firebase library itself as described [here](https://github.com/CSFrequency/react-firebase-hooks/issues/180#issuecomment-962420543), so we won't even have visibility of the internals of the data.

I would suggest that you take a look to see if you could implement this yourself or restructure your data in such a way that you are able to load each screen or component in a single read from the database.
