### ISSUE TITLE
Add ability to retry realtime database hooks in the of an error

### ISSUE THREAD

**Issue by Zanchee** [CSFrequency/react-firebase-hooks#204]
How can one reevaluate the hook if the hook fails and returns an error?

**Comment by chrisbianca** [comment]
@Zanchee the Firestore `xxxOnce` hooks have a manual `reload` function that gets returned by the hook, but no other hooks do at the moment. 

Are there particular hooks where you think this would be useful?

**Comment by Zanchee** [comment]
Ahh interesting. The firebase real-time database would be great! 😊

**Comment by chrisbianca** [comment]
@Zanchee Having reviewed this one in a bit more detail, the real-time database hooks don't have the equivalent `xxxOnce` hooks so it's not really possible to add a `reload` method.

Given the lack of requests for `xxxOnce` style hook in the real-time database, I'm not going to add this at the moment. If that changes, then I will do with the reload functionality.
