### ISSUE TITLE
useSendPasswordResetEmail  requires the user to be logged in

### ISSUE THREAD

**Issue by AndreasHaaversen** [CSFrequency/react-firebase-hooks#205]
The typical use-case for this hook is to implement "forgotten password"-type functionality. That isn't possible with the hook as is since it requires the user to log in first.

The Firebase SDK itself doesn't require a user to be logged in. I don't think we should wrap the SDK in more restrictions than it already provides.

**Comment by chrisbianca** [comment]
@AndreasHaaversen good spot, this was an oversight on my side. I'll get this resolved and a patch release out shortly.
