### ISSUE TITLE
How to use useSignInWithFacebook hook?

### ISSUE THREAD

**Issue by shikhar13012001** [CSFrequency/react-firebase-hooks#206]
I see a useSignInWithFacebook in the docs but when I use it , gives error 
```Attempted import error: 'useSignInWithFacebook' is not exported from 'react-firebase-hooks/auth'.```
please help me here thankyou.

**Comment by chrisbianca** [comment]
@shikhar13012001 which version of `react-firebase-hooks` do you have installed? You need v5 or above to use this hook.

**Comment by chrisbianca** [comment]
Closing due to lack of response, please re-open if this is still a problem
