### ISSUE TITLE
Migrating from v4 idField

### ISSUE THREAD

**Issue by Schmell** [CSFrequency/react-firebase-hooks#208]
i read this at the bottom of your docs
>This has replaced the transform, idField and refField options that were available in react-firebase-hooks v4 and earlier.
can you provide a simple example of how to implement this at least for the legacy - idField

i have been able to use useCollection and get the id, but i kind of prefer the simpler useCollectionData

**Comment by chrisbianca** [comment]
@Schmell The Firebase documentation has a nice example of how to create a converter: https://firebase.google.com/docs/reference/js/firestore_.firestoredataconverter#example. The `fromFirestore` method of the converter is passed the `QueryDocumentSnapshot` which has access to the `idField`.

Then simply specify a converter using `withConverter` on the collection and pass that into `useCollectionData` as you would previously, e.g.

```
const ref = collection(firestore, 'collectionName').converter(yourConverter);
const [data, loading, error] = useCollectionData(ref);
```

I'll close this but please let me know if this doesn't work for you.

**Comment by Schmell** [comment]
Hey thanks for your reply.
The example is confusing, like do I have to make a class to map to??
anyway I just get lots of Object possibly null errors.
I don't want to waist your time as I am just a noob.  I can just use `useCollection`
Thanks anyway

**Comment by chrisbianca** [comment]
@Schmell I have just added a full example to the documentation here: https://github.com/CSFrequency/react-firebase-hooks/tree/master/firestore#transforming-data. Hopefully this makes it clearer

**Comment by Schmell** [comment]
Hey thanks, I appreciate your input on this. 
Yes it was a better example especially for Typescript and v9
works great, I didn't even know about the `docRef ` and that is even cooler
Thanks again

**Comment by stevecastaneda** [comment]
I tried to build a generic converter that added an `id` field to all data coming from firestore based on `snapshot.id`, but what I'm seeing is that it's actually **adding** an `id` parameter to the document when I add new documents as well.

I'm solely trying to get the ID field on the client-side.  Would someone be able to tell me what I'm doing wrong here?

```
export const withIDConverter: FirestoreDataConverter<any> = {
  toFirestore(data: WithFieldValue<any>): DocumentData {
    return data;
  },
  fromFirestore(snapshot: QueryDocumentSnapshot, options: SnapshotOptions): any {
    const data = snapshot.data(options);
    return {
      id: snapshot.id,
      ...data,
    };
  },
};
```
