### ISSUE TITLE
useMemo() with its dependency being a freshly created array will never memoize

### ISSUE THREAD

**Issue by aarku** [CSFrequency/react-firebase-hooks#215]
https://github.com/CSFrequency/react-firebase-hooks/blob/ab6214822fdc0c280ea39e001db09bc2bbc5264d/firestore/useCollection.ts#L56-L61

This gets done in multiple places. I think the author thought React did a shallow compare like `React.memo()` does, but it doesn't. If `value`, `loading`, and `error` are stable, they could be the dependency array, and the inner function of `useMemo()` could construct the array.

If you want a PR let me know.

**Comment by glaucoheitor** [comment]
Is this the reason why `useCollection` and `useDocument` calls Firestore on every render?
I'm trying to avoid expensive costs and avoid query the server on every render.

**Comment by aarku** [comment]
No, I misread the code. This issue should be deleted.
