### ISSUE TITLE
Example Request: useAuthState / onAuthStateChanged listener for context provider (useEffect)

### ISSUE THREAD

**Issue by mparsakia** [CSFrequency/react-firebase-hooks#216]
Hello!

I'm trying to refactor some of my JS firebase code to use this library in a project.

I'm having one problem, and for now am using the standard method for implementing my AuthProvider in the app.

I have a component that wraps <App>, that I use as a context provider for user auth state:

``` export function AuthProvider({ children }) {
  const [authUser, setAuthUser] = useState(null);

   //...

  useEffect(() => {
    // listen for auth state changes
    const authListener = onAuthStateChanged(firebaseAuth, async (user) => {
      setAuthUser(user);
    });
    return () => {
      // unsubscribe to the listener when unmounting
      authListener();
    };
  }, [firebaseAuth]);
  
  // firebaseAuth = getAuth(firebaseApp);  in the useEffect dependency array
  // (I think this is the correct way? If I am incorrect please let me know.)

  const value = { authUser, logoutFn };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}
```

I would love to refactor this useEffect instead to use the 
`const [user, loading, error] = useAuthState(auth, options);` hook provided by this library, but it does not return the actual onAuthStateChanged.

 Is this possible, or should I stick with the method I am currently using?

**Comment by DanielBailey-web** [comment]
@mparsakia the user is already memoized. So you can just do this:
```js
  const [authUser, loading, error] = useAuthState(auth, options);

  const value = { authUser, logoutFn };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
```

**Comment by mparsakia** [comment]
@DanielBailey-web First example worked perfectly and I checked with multiple tabs open, user state is updated across all of them upon login and logout. Can't believe it was that simple, thank you 👍 Completely got rid of the useEffect, as my only use case was to update state when auth changed.
