### ISSUE TITLE
useDownloadURL not working with reference

### ISSUE THREAD

**Issue by srobertson421** [CSFrequency/react-firebase-hooks#22]
I'm trying to use the `useDownloadURL` method for a file reference in my firebase storage. Getting an array error:

![image](https://user-images.githubusercontent.com/2695134/58440300-f0310800-808d-11e9-9e2f-ac9b0a02ef3c.png)

Here is my code:

```
const [
    value,
    loading,
    error,
  ] = useDownloadURL(
    firebase.storage().ref(`avatars/eCP7rPbQbMOABgklojtQDPxFE6A3.jpeg`)
  );
```

**Comment by chrisbianca** [comment]
@srobertson421 Are you able to confirm which version of `react-firebase-hook` you're using?  This doesn't look like an error from within the library, so I'm wondering if you're using the new array returns with v1.x of the library which returns objects.

**Comment by srobertson421** [comment]
@chrisbianca Ah I was on v1.2.1, forced the update to 2 and it's working. Thanks!

**Comment by chrisbianca** [comment]
No problem, glad it's all working!
