### ISSUE TITLE
Dynamic reference depending on user custom claims

### ISSUE THREAD

**Issue by ThibaudMZN** [CSFrequency/react-firebase-hooks#221]
I need to fetch some user data, but the reference string is depending on this user's custom claims, like so : 

`/group/{userclaim}/data`

I'm struggling to use the auth and realtime database hooks for this specific use case, because the first useList() is always called while the userClaim is still empty.

Any idea or example would be greatly appreciated

**Comment by DanielBailey-web** [comment]
Is a template string not working for you?

```
const claimQuery = userclaim?`/group/{userclaim}/data\`:null
```

**Comment by chrisbianca** [comment]
As per @DanielBailey-web's reply, use a conditional on the custom claim and pass `null` to the `useList` hook whilst the custom claim is loading. The hook will load as soon as the custom claim becomes available.

**Comment by ThibaudMZN** [comment]
Thank you !

**Comment by psdewar** [comment]
@chrisbianca How would this work using state? I'm getting a race condition applying this solution to `useObject`. For example: 

```
if (someState == null) {
  setSomeState(paramsFromPrevRoute); // same result from useEffect
}
const obj = useObject(someState ? database().ref(`data`) : null);
console.log(obj);
```
```
results from console
 LOG  [undefined, true, undefined]
 LOG  [undefined, false, undefined]
 LOG  [undefined, true, undefined] // unexpected
```
Is there an alternative approach?
