### ISSUE TITLE
Suggestion for updating user In useAuthState 

### ISSUE THREAD

**Issue by Night-Hunter-NF** [CSFrequency/react-firebase-hooks#229]
I've just been using your package for Auth hooks and noticed that it has no support for update of the current user i.e. when you change email or display name the state isn't updated.

i have gone an written my own simpler way of handling Firebase Auth. but thought since you already have your own hooks for updating email, display name etc it might be worth putting in a callback that runs when ever those hooks are run that updates useAuthState user to auth.currentUser.

**Comment by chrisbianca** [comment]
Thanks @Night-Hunter-NF, this has been requested previously but I've not had a chance to tackle it yet: https://github.com/CSFrequency/react-firebase-hooks/issues/147

I'm going to close this in favour of that issue.
