### ISSUE TITLE
return hooks as object

### ISSUE THREAD

**Issue by mdsaifullah365** [CSFrequency/react-firebase-hooks#232]
react-firebase-hooks are returned as array. I think it will be more easy to destructure the proper properties or methods if they are returned as object.

**Comment by chrisbianca** [comment]
@mdsaifullah365 v1 of react-firebase-hooks did use objects, but they were dropped in favour of arrays to aid composability. With objects, it became a pain when using multiple of the same hooks as you would need to rename the object variables, 

e.g
```
const [document1, document1Loading, document1Error] = useDocumentData(...);
const [document2, document2Loading, document2Error] = useDocumentData(...);
```
is much simpler than:
```
const { data: document1, loading: document1Loading, error: document1Error } = useDocumentData(...);
const { data: document2, loading: document2Loading, error: document2Error } = useDocumentData(...);
```

Admittedly, there were fewer response variables, but I'm still in preference of the array structure for now.

**Comment by mdsaifullah365** [comment]
Now, It makes sense to me. Thanks for reviewing the issue.
