### ISSUE TITLE
firebase error doesn't work

### ISSUE THREAD

**Issue by Sazid99246** [CSFrequency/react-firebase-hooks#233]
I have used 3+ hooks of authentication hooks, but I can't implement showing errors, please check it

**Comment by samos123** [comment]
I'm having the same issue. Seems error returns an array of error objects but the examples with firebase v9 make it sound like error is undefined or a string.

**Comment by chrisbianca** [comment]
@Sazid99246 @samos123 I am going to close for now, but please feel free to reopen with an example where the errors aren't working.
