### ISSUE TITLE
Sorting and Filtering in Realtime Database

### ISSUE THREAD

**Issue by ThibaudMZN** [CSFrequency/react-firebase-hooks#235]
Hi !

Is there a way to use sorting and filtering in Realtime Database Hooks (`useList` for example), functions like `orderByChild()` or `limitToFirst()` ?

Thanks !

**Comment by rayoverweij** [comment]
Use `query()` like you would in a vanilla call to Firebase, i.e. instead of

```useList(ref(database, 'list'));```

something like

```useList(query(ref(database, 'list'), orderByChild('someChild')));```

**Comment by ThibaudMZN** [comment]
Ah that wasn't so hard !
Thanks, maybe that could be somewhere in the docs :)
