### ISSUE TITLE
useAuthState gives null

### ISSUE THREAD

**Issue by ghost** [CSFrequency/react-firebase-hooks#236]
When I am trying to get a user with useAuthState, it gives me null. How can i fix this?

**Comment by HaakonStromsnes** [comment]
Hi, is the user logged in? And do you pass in the firebase auth config as an argument in the useAuthState?

**Comment by faisalchy64** [comment]
> Hi, is the user logged in? And do you pass in the firebase auth config as an argument in the useAuthState?

Yes, user logged in and pass firebase auth perfectly

**Comment by HaakonStromsnes** [comment]
Then it's hard to say what's wrong without seeing the code. useAuthState works like it should for me. The only issue I have is the error not working

**Comment by chrisbianca** [comment]
@ghost please feel free to reopen with a code example where this isn't working
