### ISSUE TITLE
Error in documentation of useSignInWithEmailAndPassword

### ISSUE THREAD

**Issue by a-barbieri** [CSFrequency/react-firebase-hooks#239]
https://github.com/CSFrequency/react-firebase-hooks/blob/edab3f3f3b5ec01c8aafcc6096755dfcc69e4408/auth/README.md?plain=1#L150

In the docs you use `user.email` but `useSignInWithEmailAndPassword` returns UserCredential type not User.
The correct use should be `user.user.email`. It might be good to rename it then...

**Comment by a-barbieri** [comment]
The same goes for `useCreateUserWithEmailAndPassword`

**Comment by chrisbianca** [comment]
Thanks @a-barbieri, I have updated the documentation
