### ISSUE TITLE
Why react-firebase-hooks does not include useSignInWithPhoneNumber or  useSignInWithEmail?

### ISSUE THREAD

**Issue by msalahz** [CSFrequency/react-firebase-hooks#243]
Why react-firebase-hooks does not include useSignInWithPhoneNumber or  useSignInWithEmail?

**Comment by chrisbianca** [comment]
`useSignInWithPhoneNumber` is rather complex to implement.
`useSignInWithEmail` is already supported here: https://github.com/CSFrequency/react-firebase-hooks/blob/master/auth/README.md#usesigninwithemailandpassword
