### ISSUE TITLE
Use undefined instead of void

### ISSUE THREAD

**Issue by davewasmer** [CSFrequency/react-firebase-hooks#26]
It looks like the loading utility hook types the `value` property as `void`. This makes it difficult to work around potential edge cases in the code:

```ts
  let [ user, userIsLoading, userError ] = useAuthState(firebase.auth());
  if (userIsLoading) {
    return null;
  }
  // do something with user ...
  user.someProperty; // <- errors with "someProperty doesn't exist on type void | User"
```

The problem here is that, because `user` is typed as possibly being `void` (which is different from `undefined`), I can't even do something like `user!.someProperty` to assure TS that the variable will have a value.

I think the fix here is to switch to `undefined` as the fallback type.

**Comment by nhagen** [comment]
Outside of typescript this results in being unable to do basic default parameters like:

```
const [ company = {} ] = useDocumentData(docRef)
```

because company is `null` and default values are only set on undefined

**Comment by chrisbianca** [comment]
Thanks for flagging this, and sorry that it's taken me so long to address.  I've just pushed up a commit: https://github.com/CSFrequency/react-firebase-hooks/commit/f2ebfc3efb062eeb3d427263f53efd342a8375a8

I'll get a release out later today which includes this.

**Comment by chrisbianca** [comment]
This is now published: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v2.1.0
