### ISSUE TITLE
add enabled flag for firestore

### ISSUE THREAD

**Issue by hussamkhatib** [CSFrequency/react-firebase-hooks#260]
fetch only if enabled is true, 

Coinsider the example
```js
  const [value, loading, error] = useDocument(
    doc(firestore, "users", useruid)
  );
```

adding  a optional flag to fetch only when useruid is defined
```js
  const [value, loading, error] = useDocument(
    doc(firestore, "users", useruid),
    {
      enabled: useruid,   // make a network request if only Boolean(useruid)  is true
    }
  );
```

If required, I am willing  to contribute

**Comment by kaueDM** [comment]
#110

**Comment by chrisbianca** [comment]
@hussamkhatib As per #110, the approach used by this library is to support the passing of null / undefined to the hook to prevent loading
