### ISSUE TITLE
useIdToken not found in 'react-firebase-hooks/auth'

### ISSUE THREAD

**Issue by vm02** [CSFrequency/react-firebase-hooks#278]
I get the error message "Module '"react-firebase-hooks/auth"' has no exported member 'useIdToken'.".
It should be included in version 5.1.0 of the package. I'm already on this version.
I think it is missing in the "index.d.ts" file under the "react-firebase-hooks/auth/dist/auth/" path.

Edit:
I saw there is already a PR opened: https://github.com/CSFrequency/react-firebase-hooks/pull/277

**Comment by chrisbianca** [comment]
The PR has now been merged and v5.1.1 has been published with the fix. Sorry for the oversight on my part.
