### ISSUE TITLE
Logout on Reload.

### ISSUE THREAD

**Issue by uttamsaha** [CSFrequency/react-firebase-hooks#279]
I get logout when I reload the website. What's the solution?

**Comment by AR-Shahin** [comment]
"useAuthState loading to solve this problem" const [user, loading, error] = useAuthState(auth, options);

**Comment by AR-Shahin** [comment]
> I get logout when I reload the website. What's the solution?

"useAuthState loading to solve this problem" const [user, loading, error] = useAuthState(auth, options);

**Comment by uttamsaha** [comment]
> > I get logout when I reload the website. What's the solution?
> 
> "useAuthState loading to solve this problem" const [user, loading, error] = useAuthState(auth, options);
Thank you. I forgot about that suddenly I got remembered.
