### ISSUE TITLE
initialising and error not working on Auth Hook

### ISSUE THREAD

**Issue by HausOfAlejandro** [CSFrequency/react-firebase-hooks#29]
Hello there! :-)

I'm using the same code provided as example and the **initialising** and **error** states are never reached... login and logout are working fine.

Just found a [related topic](https://github.com/CSFrequency/react-firebase-hooks/issues/1), but I installed the "react-firebase-hooks" packpage today so it shouldn't be happening.

**Comment by chrisbianca** [comment]
@HausOfAlejandro can you check your `package-lock.json` or `yarn.lock` to see what version of `react-firebase-hooks` has been installed?

**Comment by HausOfAlejandro** [comment]
> @HausOfAlejandro can you check your `package-lock.json` or `yarn.lock` to see what version of `react-firebase-hooks` has been installed?

Hi! is ^2.0.0

**Comment by chrisbianca** [comment]
Closing as I cannot reproduce

**Comment by ynnoj** [comment]
@chrisbianca This is a widely reported issue facing multiple users (#43, #46).

Using the example in the `useAuthState` README is a clear reproduction. Please can you investigate this further.

**Comment by slk333** [comment]
@ynnoj did you find a solution?
Ran into the exact same issue.
Can't believe fireship.io actually recommended this package

**Comment by ynnoj** [comment]
> @ynnoj did you find a solution?
> 
> Ran into the exact same issue.
> 
> Can't believe fireship.io actually recommended this package

Nope. Just using the Firebase SDK directly.

**Comment by pvhieuit** [comment]
Same issue

**Comment by lorstenoplo** [comment]
@chrisbianca I have fixed this issue in PR : #98 , please check if it can be merged
