### ISSUE TITLE
How to get the access token

### ISSUE THREAD

**Issue by hxhieu** [CSFrequency/react-firebase-hooks#32]
Hi,

Is there away to get the provider access token? Since we can only get it right after sign in and I cannot find any documentation on how to get it with our auth hooks.

Thanks,
H

**Comment by chrisbianca** [comment]
@hxhieu unfortunately Firebase does not provide any way to get the access token from the User object, you'll need to intercept this after sign in.

**Comment by akoenig** [comment]
@hxhieu You can access the token by evaluating the result after signing in:

```typescript
const login = async () => {
    const provider = new firebase.auth.GithubAuthProvider();

    const { credential } = await firebase.auth().signInWithPopup(provider);

    // Use `credential.accessToken` for communicating with the GitHub API.
  };
```
