### ISSUE TITLE
Utils not bundled with react-firebase-hooks/firestore

### ISSUE THREAD

**Issue by asibilia** [CSFrequency/react-firebase-hooks#37]
`import { useCollection } from 'react-firebase-hooks/firestore';`

Results in this error:  `cannot find module ../util`

Called by `.../node_modules/react-firebase-hooks/firestore/dist/firestore/useCollection.d.ts`

**Comment by chrisbianca** [comment]
@asibilia this is a duplicate of #28 . Would you be able to add some more information about your project setup to #28 to help us debug?
