### ISSUE TITLE
Duplicate from reactfire

### ISSUE THREAD

**Issue by Lucas-Geitner** [CSFrequency/react-firebase-hooks#40]
Hello everyone, 

just wondering if this repo is not just a duplicate (with few functions more) of https://github.com/FirebaseExtended/reactfire which also include hook

Thanks you very much

**Comment by chrisbianca** [comment]
@Lucas-Geitner this library was created before work on ReactFire was restarted. It looks like the new version of ReactFire is still in alpha, but definitely worth keeping an eye on.
