### ISSUE TITLE
Feature request for useCollection and useDocument - latest result timestamp

### ISSUE THREAD

**Issue by bgarrett-rt** [CSFrequency/react-firebase-hooks#42]
I really appreciate the work on this library.

I have one feature request. Is it reasonable to add a timestamp field to the return array? 
So for example [value, loading, error, timestamp] = useCollection(...)

My use case is that I often use the last modified timestamp on a document to trip React caching in useEffect, useMemo, etc. However, this requires logic to look at the docs to see if any of them were modified in order to update the cache arguments to useEffect to do some processing. For most of my use cases, I could easily use the timestamp from the last time the FB onSnapshot event was triggered.

**Comment by chrisbianca** [comment]
@bgarrett-rt This is a fairly niche feature request that hasn't gained much support. I'm loathe to overcomplicate the API with little used features, so I'm going to close this, sorry.
