### ISSUE TITLE
How to use multiple hooks that depend on each other?

### ISSUE THREAD

**Issue by dannytatom** [CSFrequency/react-firebase-hooks#44]
Example:

```typescript
const [authUser, authLoading, authError] = useAuthState(firebase.auth());
const [user, userLoading, userError] = useDocument(firebase.firestore().doc(`users/${authUser.uid}`));
```

I can't put `useDocument` in a `if (authUser)` because React breaks with: `Rendered more hooks than during the previous render.`

**Comment by renzhentaxi** [comment]
All hooks needs to be top level (this comes from react itself).

What you can do is something like this:
`useDocument( () => if (authUser) firebase.firestore().....)`

**Comment by dannytatom** [comment]
@renzhentaxi `useDocument` only accepts a DocumentReference, though, so I can't do that. Also can't, like, store `authUser` in state with `useState` then use that because infinite loop.

**Comment by dannytatom** [comment]
I saw that, but I guess I'm kind of confused. What I have now is similar to that, I think? But I get: `Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`

```typescript
const UpgradeButton: React.FC = () => {
  const toast = useToast();
  const [user, userLoading, userError] = useAuthState(firebase.auth());
  const [userDoc, userDocLoading, userDocError] = useDocument(user && firebase.firestore().doc(`users/${user.uid}`));

  if (userLoading || userDocLoading) {
    return null;
  }

  if (userError) {
    toast(getErrorToastConfig("Unable to sign in."));

    return null;
  }

  if (userDocError) {
    toast(getErrorToastConfig("Unable to get user data."));

    return null;
  }

  if (userDoc) {
    const userData = userDoc.data();

    if (userData && userData.basic) {
      return <Button size="sm">Upgrade</Button>;
    }
  }

  return null;
};

```

**Comment by ebemunk** [comment]
this is the pattern i use a lot, in a hook called `useUser` so I don't duplicate it as much, basically looks like this
```
  const [auth, authLoading, authErr] = useAuthState(firebase.auth())
  const [data, dataLoading, dataErr] = useDocumentData(
    auth ? firebase.firestore().doc(`users/${auth.uid}`) : null,
  )
```
i dont think `useDocumentData(auth && firebase.firestore()...)` usage is correct
