### ISSUE TITLE
Readme example: Can login and logout functions be moved outside?

### ISSUE THREAD

**Issue by callumlocke** [CSFrequency/react-firebase-hooks#45]
In the main example in the readme, `CurrentUser` creates new `login` and `logout` functions on every render. Is this necessary somehow, due to the way React hooks work, or can these functions be safely moved outside?

**Comment by rahsheen** [comment]
Looks like they don't depend on the component at all so could be moved out.

**Comment by chrisbianca** [comment]
I've updated the documentation, thanks for flagging
