### ISSUE TITLE
Proposal: apply transformations to returned object(s)

### ISSUE THREAD

**Issue by imjared** [CSFrequency/react-firebase-hooks#52]
Still fleshing the idea out but wanted to note in case there was interest. It'd be handy for our use case to be able to apply transformations to returned object(s). Often times the data we have stored is not necessarily the data we want to display so we often wind up running the same transformations after fetch.

### A few examples:

- Our users always have a `first_name` and a `last_name`. Sometimes they also have a `display_name`. We always want the `display_name` to take precendence and run a transformation on retrieved data to do so.

- We use Firebase timestamps which are really handy on the server and really not-so-handy on the client since they always need to be coerced with at least `.toDate()`

- Currency formatting always winds up with something like `.toLocaleString()` or something. I can't even remember off the top of my head and would need to look into our codebase for how we typically format.

### Suggested enhacnement
Provide a `transformations` property in `options` that all data is run through. A `transformation` could either be added to an object or overwrite a property of an incoming object.

For example, let's say my source object is a user:
```js
{
  first_name: 'John',
  last_name: 'Smith',
  created_at: firebase.firestore.Timestamp
}
```

With `transformations`:
```js
const [user, userLoading, userError] = useDocumentData(
  myCollectionRef.users('1234')
, {
  transformations: {
    display_name: (data) => {
      return data.display_name 
        ? data.display_name 
        : `${data.first_name} ${data.last_name}`
    },
    created_at: (data) => {
      return data.created_at.toDate().toDateString();
    }
  }
})
```

Expected output from `console.log(user)`:
```js
{
  first_name: 'John',
  last_name: 'Smith',
  display_name: 'John Smith',
  created_at: 'Wed Dec 18 2019',
}
```

I could see this coming in handy for us since we could store a handful of "schema" transformations and add to them with spread syntax. eg.

```js
{
  transformations: {
    randomOneOffProp: (data) => data.field.toLowercase(),
    ...commonPeopleTransformsFromFile,
  }
}
```

Ideally the same could be applied to collection data

**Comment by luchux** [comment]
@imjared you can write your own hook for that functionality and keep it out of this library. 
I think it separate more the responsibilities since firebase does not provide those transformations and this lib seems very 1-1 to firebase.

**Comment by imjared** [comment]
point taken, luciano. since requesting this feature i've found that firestore provides [DataConverters](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter) which probably meet my need

**Comment by imjared** [comment]
looks like this was handy, after all:
https://github.com/CSFrequency/react-firebase-hooks/tree/master/firestore#transforming-data
