### ISSUE TITLE
Refresh data for useDocumentDataOnce

### ISSUE THREAD

**Issue by deiucanta** [CSFrequency/react-firebase-hooks#53]
I couldn't find anything about refreshing data for a document that is loaded using `useDocumentDataOnce`. My app will have a refresh button or a pull-to-refresh gesture.

I tried using a dummy local state to force the re-render but it doesn't work since the document refs are the same across renders.

```js
const [refreshCount, setRefreshCount] = useState(0);
const refresh = () => setRefreshCount(refreshCount + 1);
```

Is this possible to implement this behaviour?

**Comment by nmaves** [comment]
Don't use Once.  Just use useDocumentData().  It will refresh it for you when the data in the Firestore Database changes.

**Comment by MartinSeeler** [comment]
Maybe it would be possible by passing a `fetch` method down by `useDocumentDataOnce `? It could be called internally on create but let the use re-run the fetch when it's needed?

**Comment by chrisbianca** [comment]
As per the answers already, if you need to refresh the data, use the `useDocumentData()` hook
