### ISSUE TITLE
Auth user email Verification changes doesn't triggers re-render

### ISSUE THREAD

**Issue by pikilon** [CSFrequency/react-firebase-hooks#57]
Thanks for this library I guess this issue is related with `Firebase/auth` itself and not the hook but this is the journey:

### Steps to reproduce
1. Not register user go to a registration form in Tab1
2. the Registration form shows a `user.emailVerified: false` on the top 
3. The user register using the form
4. A verification email is sent to the user
5. The form now shows a message pending verify email
6. The user goes to the email and clicks in the verification link opening Tab2

### Current result

- Returning to the Tab1 the message `user.emailVerified: false` remains
- if in the console I access the `user` entity  `user.emailVerified -> true`

### Expected result
`user.emailVerified` changes triggers a component re-render
- Returning to the Tab1 the message is `user.emailVerified:  true`

**Comment by awoodall** [comment]
Was testing this out as well and it looks like `auth().onAuthStateChanged()`doesn't detect an update when `emailVerified` is changed.

One potential solution would be to call on [auth().currentUser.reload()](https://firebase.google.com/docs/reference/js/firebase.User.html#reload) on a set interval until `emailVerified` is true.

Another solution would be to track the verified status under a firestore document (e.g. `profile/user_uid`) and using a [custom action handler](https://firebase.google.com/docs/auth/custom-email-handler) update the user's verified status on verification.

**Comment by chrisbianca** [comment]
Yes, unfortunately this is a known issue with the underlying Firebase library, so there's not much we can do to address it within this library.

The solutions suggested by @awoodall would work nicely.
