### ISSUE TITLE
Querying nested data

### ISSUE THREAD

**Issue by mchong-teal** [CSFrequency/react-firebase-hooks#58]
Hi, I have some data structured something like the following:

- Root doc
    - Middle collection of node docs (only 1 layer deep for now)
        - Collection of leaf docs

Normally, I might break this up into separate components that each have their own hook, but I am using a library that accepts the data in hierarchical form.  Is there a way I can query the whole structure at once?  Alternatively, do people have best practices for structuring data like this so it can be queried in parts and then assembled in an efficient way (for reading, say)?

Playing around with it now, may update with work in progress as I go.

**Comment by mchong-teal** [comment]
I think this might be more of a firestore question, but I think my solution is to have a root level collection of middle nodes and leaves, and each node as an array of references to their children (a list of ids, probably not reference types..)

**Comment by luchux** [comment]
@mchong-teal This does not seems to be an issue.  Please refer the documentation as mentioned here. And if you can close this issue, will be fantastic for the maintenance of the project. 

You can do that in firebase with relationships, and query in a proper way. Please check https://firebase.google.com/docs/firestore/manage-data/structure-data  and the relevant querying methods (but you can do firestore().collection('parent').doc(id).collection('children') etc as the relationships you define in the structure.

**Comment by luchux** [comment]
@mchong-teal  now you can query subcollections with group collections queries. There is not a hook from what I guess, but it doesn´t matter becuase you can write your query like this an passit to a hook like useCollectionDataOnce, etc. 
https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

**Comment by chrisbianca** [comment]
Closing as this is a data structure / usage question rather than an issue with the library.
