### ISSUE TITLE
Getting delayed/no response on mobile

### ISSUE THREAD

**Issue by baebb** [CSFrequency/react-firebase-hooks#60]
Hi!

Use this lib for a project with mainly mobile users. In development on simulated iOS and android updates to the document I'm watching are seen immediately but on real devices there is a significant lag, but is solved by a refresh of the page. 

Any ideas what I can do to solve?

**Comment by drtapha** [comment]
i have same problem with firebase.auth().signInWithEmailAndPassword

**Comment by zano-aa** [comment]
Hi guys,

Do you know if those issue regarding react-native and firebase has been fixed yet ?

**Comment by chrisbianca** [comment]
I'm afraid that this is going to be an underlying issue with Firebase and not with the hooks, as they are simply passing on the responses as they are received.
