### ISSUE TITLE
Query using date comparator causes constant component reload

### ISSUE THREAD

**Issue by Rob5Underscores** [CSFrequency/react-firebase-hooks#61]
When using a query containing the 'where date' clause as below, the data loads correctly but the component and its children are constantly reloaded. Removing the `.where('date', '>', Firebase.firestore.Timestamp.now())` stops this happening. I migrated to this project from another and this logic worked correctly there.

Is there anything I'm doing wrong?

Thanks

`
    const withEvents = Component => props => {
        const provider = useContext(CalProvider);
        const _class = useContext(ClassProvider);

        console.log('withEvents loading');
        const [values, loading, error] = useCollectionData(
            Firebase.firestore()
                .collection(`providers/${provider.id}/events`)
                .where('classId', '==', _class.id)
                .orderBy('date', 'asc')
                .limit(4),{idField:'id'}
        );
        if (error) return <Error error={error} />;
        if (loading) return <CircularProgress />;
        
        if (values.length === 0) return <NoEvents />;

        return (
            <EventsProvider.Provider value={values}>
                <Component>{props.children}</Component>
            </EventsProvider.Provider>
        );
    };`

**Comment by ROODAY** [comment]
+1 I get the same issue with `const [deals, loading, error] = useCollectionData(firebase.firestore().collection('deals').where("expires", "<=", now));`

**Comment by nmaves** [comment]
This one seems pretty obvious.  Your `now` is changing on every re-render of your component.  Post your entire component so we can help more.  I would think something like the following might work better.

```javascript
const [now] = useState(() => new Date())
```

You can find the docs for that [here](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state)

**Comment by ROODAY** [comment]
Oof, I believe that was the error for me! I ended up not using this library as I needed to convert my component into a class anyways, but now my `now = new Date()` is in componentDidMount which is probably why I'm not getting endless re-renders. Thanks!

**Comment by Rob5Underscores** [comment]
> This one seems pretty obvious. Your `now` is changing on every re-render of your component. Post your entire component so we can help more. I would think something like the following might work better.
> 
> ```js
> const [now] = useState(() => new Date())
> ```
> 
> You can find the docs for that [here](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state)

I also ended up not using this library so can't confirm whether or not this was the problem.

Thanks for your help.
