### ISSUE TITLE
Request: useCollectionGroup and useCollectionGroupData

### ISSUE THREAD

**Issue by Wgil** [CSFrequency/react-firebase-hooks#63]
Hey!

Great lib! Wondering if it would be useful to add `useCollectionGroup` and `useCollectionGroupData`.

Use case: querying a single document using a `collectionGroup` query.
Example:

```tsx

const SomeCollectionComponent = ({ someId }) => {
  // useDocument cannot be used since `useDocument` expects a `DocumentReference<DocumentData>` and my query returns a `Query<DocumentData>`
  [snapshots, error, loading] = useCollectionData(
    firebase
      .firestore()
      .collectionGroup('someCollection')
      .where('id', '==', someId)
  )

  // After rror and loading checks

  const document = snapshots[0]

  // do something with document
}

```

Proposed implementation:
```tsx
useCollectionGroupData = (query) => {
  const [snapshots, loading, error] = useCollectionData(query)

  return [snapshots && snapshots[0], loading, error]
}
```

Lemme know if I can work on this!
Cheers

**Comment by luchux** [comment]
Just for reference: 
https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html

**Comment by joshuamckenty** [comment]
I would second this - definitely need collectionGroup support. Thanks!

**Comment by jerrybuks** [comment]
can i go ahead, and implement these hooks (useCollectionGroupData and useCollectionGroup)?

**Comment by chrisbianca** [comment]
Sorry for the delayed response on this. I've just taken a look and it appears that collection groups are already supported by the `useCollection` and `useCollectionData` hooks already:

```
const ref = firebase.firestore().collectionGroup('myPath');
const [value, loading, error] = useCollection(ref);
```

If you feel this isn't the case, please feel free to re-open with further information.

**Comment by jelling** [comment]
An edge case note in hopes of saving someone else some time: 

- Firebase provides a UI for creating a Collection Group, except maddeningly the UI does not always create them properly as certain business rules are not part of the UI design. But it will still tell you that it successfully created.

- Instead, Firebase recommends creating Collection Groups by issuing a query that will then generate a console error with a link that will then actually create the Collection Group properly

- At least in my case, this library swallowed said helpful / hacky console error message. Instead, it just returned no data and no error.

So to fix things, I had to run a collection group query the usual Firebase way, get the console error, and then follow the link to properly create the collection group.

Hope this helps.
