### ISSUE TITLE
useCollectionData always returns new values in array

### ISSUE THREAD

**Issue by petrkrejcik** [CSFrequency/react-firebase-hooks#66]
`useCollectionData` returns new items in the array every time when a hook is called. This makes it impossible to perform an equality comparison on the values in the array because the values are always newly created.

**Example:**
```js
const ComponentA = () => {
  const [value, loading] = useCollectionData(db.collection(`myCollection`));
  if (loading) return null
  return <ComponentB value={value} />
}

const ComponentB = (props) => {
  const firstItem = value[0]
  
  useEffect(() => {
    // effect is called always because firstItem is always different
  }, [firstItem])
}
```

**Workaround:**
I've made a custom hook which stores *data* to a local state.

```js

export const useColData = (query, options) => {
  const [data, setData] = React.useState([]);
  const [value, loading, error] = useCollection(query, options);
  
  React.useEffect(() => {
    if (!value) return;
    setData(
      value.docs.map((doc) => {
        const docData = { ...doc.data() };
        if (options.idField) {
          docData[options.idField] = doc.id;
        }
        return docData;
      })
    );
  }, [value, options.idField]);

  return [data, loading, error];
};
```

Is it possible to change implementation of `useCollectionData` to return always the same items in the array if the query result is not changed?

**Comment by chrisbianca** [comment]
This has been fixed by https://github.com/CSFrequency/react-firebase-hooks/pull/41 and is part of version 2.2.0
