### ISSUE TITLE
Request: add generics to mirror firestore and improve type safety

### ISSUE THREAD

**Issue by ehahn9** [CSFrequency/react-firebase-hooks#67]
react-firebase-hooks rocks, btw -- thanks!

slight (trivial) suggestion:

```ts
// current
export const useDocument = (
  docRef?: firestore.DocumentReference | null,

// proposed
export const useDocument<T = firestore.DocumentData> = (
  docRef?: firestore.DocumentReference<T> | null,
```

this would also apply to `useCollection`, etc.

This would be helpful because firestore does indeed preserve the type all the way to the subsequent snapshot `data()` value.

As a side-benefit,  a typed `ref` would improve the `useDocumentData` API allowing you to deduce the returned data type without the explicit generic:

```ts
// current
const [data, loading, error] = useDocumentData<MyData>(ref);

// becomes (optional, if your ref happens to be typed)
const [data, loading, error] = useDocumentData(myDataRef); // myDataRef is DocumentReference<MyData>

```

ps: best practice would still be to validate the payload with `yup` etc. but this would go a long way!

**Comment by chrisbianca** [comment]
@ehahn9 thanks for the suggestion and apologies it's taken so long to incorporate. This will be part of the upcoming v3 release in the next week or so.

**Comment by chrisbianca** [comment]
This has now been released in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1
