### ISSUE TITLE
Waiting for the result to get a second hook

### ISSUE THREAD

**Issue by cdedreuille** [CSFrequency/react-firebase-hooks#69]
I was wondering if there was a way to use this library to do async requests in multiple hooks. In my use case, I'm calling a document that has the id for another document and I need this id to get the other document.

```
const [selectionData, loadingS] = useDocumentData(firestore.doc(`selections/${selection}`), { idField: 'id' })
const [friendData, loadingF] = useDocumentData(firestore.doc(`friends/${selectionData.id}`), { idField: 'id' })
```

Before I was using a custom hook with an async function but I was wondering there was a way to do it with your library.

To give a bit of context on what I'm trying to achieve, this code do the trick for now:

```
function useOccasion() {
  const [occasionData, setOccasionData] = useState(null)
  const [friend, setFriend] = useState(null)
  let { occasion } = useParams()

  useEffect(() => {
    const unsubscribe = firestore.collection('occasions').doc(occasion)
      .onSnapshot(async eventData => {
        setOccasionData({id: eventData.id, ...eventData.data()})
        
        let friendData = await firestore.collection("friends").doc(eventData.data().friend).get();
        setFriend({id: friendData.id, ...friendData.data()});
      })
    return () => unsubscribe()
  }, [occasion])
  
  return [occasionData, friend]
}
```

So if there's a way to reproduce this with these hooks that would be amazing.

**Comment by danaugrs** [comment]
Hey, see https://github.com/CSFrequency/react-firebase-hooks/issues/59#issuecomment-603232646. So basically:
```javascript
const [selectionData, loadingS] = useDocumentData(firestore.doc(`selections/${selection}`), { idField: 'id' })
const [friendData, loadingF] = useDocumentData(selectionData && firestore.doc(`friends/${selectionData.id}`), { idField: 'id' })
```

**Comment by cdedreuille** [comment]
Thanks a lot @danaugrs. It would be great to add this to the doc. I can imagine I'm not the only one thinking about it.
