### ISSUE TITLE
Firestore: How to fetch data to init state?

### ISSUE THREAD

**Issue by ynotu** [CSFrequency/react-firebase-hooks#70]
Consider this example:
Categories are stored in firestore. I need to display checkboxes to select these categories, so I need to store the checked state. My approach results in an infinite loop: 
Inside my component function:

```
const [categories] = useCollectionDataOnce(
		firestore.collection('categories'),
		{idField: 'id'},
	);

	const [categoriesBoxesValues, setCategoriesBoxesValues] = useState([]);

	useEffect(() => {
		if (!categories) {
			return;
		}

		const boxes = categories
		.map(c => ({
			isChecked: false,
			...c,
		}))

		// fixme: causes infinite loop
		// setCategoriesBoxesValues(boxes);
	}, [categories]);
```

Seems to be a common use case, namely to enhance a value fetched from firestore. How to solve this issue?

**Comment by Banb4n** [comment]
Hi @ynotu, i hope you've already solve your problem, but this will maybe help you: 


```js
  const [categories, loading, error] = useCollectionDataOnce(
    firestore.collection('categories'),
    {idField: 'id'},
  );
  
  const [categoriesBoxesValues, setCategoriesBoxesValues] = useState([]);
  
  useEffect(() => {
    if (!!categories && !loading) {
      const boxes = categories
      .map(c => ({
        isChecked: false,
        ...c,
      }))
      // fixme: causes infinite loop
      setCategoriesBoxesValues(boxes);
    }
  }, [loading]);

```

**Comment by chrisbianca** [comment]
Closing as @Banb4n has answered the question with one approach. There is also a new `transform` option for Firestore hooks which will be part of the next release that would allow this to be done as part of the initial hook data load. See: https://github.com/CSFrequency/react-firebase-hooks/tree/master/firestore#transforming-data

**Comment by Banb4n** [comment]
> Closing as @Banb4n has answered the question with one approach. There is also a new `transform` option for Firestore hooks which will be part of the next release that would allow this to be done as part of the initial hook data load. See: https://github.com/CSFrequency/react-firebase-hooks/tree/master/firestore#transforming-data

The `transform` option seems to be a really useful feature, thanks @chrisbianca

**Comment by tnoetzel** [comment]
@Banb4n @chrisbianca - Doesn't that approach violate the [exhaustive dependencies requirement](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies)?
