### ISSUE TITLE
Feature request for SnapshotOptions

### ISSUE THREAD

**Issue by ahoward2** [CSFrequency/react-firebase-hooks#78]
Great library.

There is currently snapshotListenOptions, and it would be super nice to include [snapshotOptions](https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotOptions) to control the return value for server timestamps that haven't yet been set to their final value.

Seems like this would be incredibly easy to implement. Let me know what you think!

**Comment by chrisbianca** [comment]
@ahoward2 good suggestion, and something I'd missed being introduced to Firestore. Apologies for the delay in resolving, but this will be included in the upcoming v3 release.

**Comment by chrisbianca** [comment]
This has now been released in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1
