### ISSUE TITLE
useCollectionOnce, useDocumentOnce

### ISSUE THREAD

**Issue by tograd** [CSFrequency/react-firebase-hooks#8]
Could be useful I think?

**Comment by chrisbianca** [comment]
This seems like a sensible suggestion, I'll try and take a look over the next couple of days, or happy to accept a PR if you're interested in taking a look yourself?

**Comment by chrisbianca** [comment]
`useCollectionOnce` and `useDocumentOnce` have been added as part of the v1.2.0 release: https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v1.2.0

Thanks for the suggestion!
