### ISSUE TITLE
If the component rerenders using same query does an API call to firestore occur?

### ISSUE THREAD

**Issue by dreamerchandra** [CSFrequency/react-firebase-hooks#82]
```
const [input, setInput] = useState();
  const [debouncedQuery] = useDebouncedCallback(queryBasedOnCustomerName, TYPING_SPEED.AVERAGE, {
    leading: false,
    trailing: true,
  });
  const [value, loading, error] = useCollectionDataOnce(debouncedQuery(input || ''), {
    idField: 'id',
  });
```
If the above snippet is used in a component whenever it gets rerendered I could see a new API hit being made...
Are there any ways to stop or memorize the result of if the query is the same? I couldn't find any ways in documentation also I tried using debounce and no effect found

**Comment by rolznz** [comment]
Any update on this? going to a different page in the app but having to wait for the exact same data to load is a poor user experience.

**Comment by caleb-harrelson** [comment]
Firestore supports [offline persistence](https://firebase.google.com/docs/firestore/manage-data/enable-offline), which would cause the second query to be loaded from the offline cache. It would still query the remote API on the second load to see if the data is stale, but would only update stale data; you'd have the non-stale data before the API request resolves. 

If you are not using offline persistence you are asking for the same data twice, without subscribing to changes, so I believe it would fetch it twice. You could store it yourself locally (redux, async storage, context api, etc.) to avoid this if you wanted.

**Comment by dreamerchandra** [comment]
@caleb-harrelson 
## Reg Store manager: 
It isn't going to change anything as `useCollectionDataOnce` would make a query and since it's a hook I can't conditionally call based upon store value

## Reg useMemo: 
From docs 
```
In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.
```
useMemo is bound to lose memorized value based on LRU

## Reg offline persistence
Yes it works but the problem is `input` is supposed to change based on user input

**Comment by caleb-harrelson** [comment]
Using a local store of some kind would prevent the delay in having the data, but not the API call itself.

Using `useMemo` works the vast majority of the time. "Write your code so that it still works without useMemo — and then add it to optimize performance." <-- that's exactly what you'd be doing here. If `useMemo` drops the cache it would do another query to fetch it, but if it has the cache you could avoid the API call. PR #79 memoizes return values, but you might need to pull the code in yourself since it's been pending for a long time.

I don't understand the issue you're raising with offline persistence. It won't be bothered by the number of queries you make, so long as the total offline cache isn't exceeded.

**Comment by dreamerchandra** [comment]
Imaging a component with 2 states where one rep userInput (typical input tag) and another rep some other state some drop-down for instance.. Ideally, you want to suggest based on user input.. since drop-down is tied to the same component you would end up querying whenever drop-down state changes too which is exactly what happened in my case

**Comment by caleb-harrelson** [comment]
PR #79 does implement memoization like that.

**Comment by chrisbianca** [comment]
Closing as this as the memoization changes from #79 will fix any unnecessary re-renders as part of v3
