### ISSUE TITLE
loading and error not working on Auth Hook

### ISSUE THREAD

**Issue by slk333** [CSFrequency/react-firebase-hooks#85]
"react-firebase-hooks": "^2.2.0",

You provided a sample code that I used as a component. Here's the component:
```jsx

import React from "react";
import { useAuthState } from 'react-firebase-hooks/auth';



export default function CurrentUser({firebase}){
  const login = () => {
    firebase.auth().signInWithEmailAndPassword('test@test.com', 'password');
  };
  const logout = () => {
    firebase.auth().signOut();
  };


  const [user, loading, error] = useAuthState(firebase.auth());

  if (loading) {
    return (
      <div>
        <p>Initialising User...</p>
      </div>
    );
  }
  if (error) {
    return (
      <div>
        <p>Error: {error}</p>
      </div>
    );
  }
  if (user) {
    return (
      <div>
        <p>Current User: {user.email}</p>
        <button onClick={logout}>Log out</button>
      </div>
    );
  }
  return <button onClick={login}>Log in</button>;
};
```

I get the following error
`
Uncaught Error: The error you provided does not contain a stack trace.
    at S (index.js:1)
    at V (index.js:1)
    at index.js:1
    at index.js:1
    at u (index.js:1)
`

the UI is supposed to display the error, as a `<p>Error: {error}</p>`, but the UI is not showing the error message.
the UI is also supposed to display the loading, but it does not. The only thing it does is displaying `<p>Current User: {user.email}</p> correctly`

It seems that more than 5 different people took the time to come on this repo to talk about this issue.
Maybe the problem lies somewhere not obvious? But again, I just used the sample code, and this is on a project that works when I don't use your hook.

Hope you can sort it out, GL

**Comment by lorstenoplo** [comment]
You can solve the problem by using `catch()` in your `signInWithEmailAndPassword` method, plus the error which the hook provides is just when your project is deleted or if google is not able authenticate requests using your API key.
