### ISSUE TITLE
Hooks doesn't show missing indexes errors

### ISSUE THREAD

**Issue by cdedreuille** [CSFrequency/react-firebase-hooks#87]
Here is an example I'm using:
```
const [messages, loading] = useCollectionData(
    firebase
      .firestore()
      .collection('chats')
      .where('user', '==', user.id)
      .orderBy('createdAt'),
    { idField: 'id' }
  );
```
If I do `console.log(messages)` I will receive `undefined` even after loading. The problem is that it's requiring a custom index in Firebase. Usually firebase gives you a nice error with a link to create this index but with the hook I don't see those errors making it really hard to debug.

**Comment by dbanisimov** [comment]
@cdedreuille the third value in the returned tuple is the error:
```js
const [messages, loading, error] = useCollectionData(
    firebase
      .firestore()
      .collection('chats')
      .where('user', '==', user.id)
      .orderBy('createdAt'),
    { idField: 'id' }
  );

useEffect(() => {
    console.error(error);
}, [error])
```

**Comment by cdedreuille** [comment]
Ah! thanks a lot. I don't know how I could have missed that. It would be great it if it can show the errors automatically as many times I end ended up missing those.
