### ISSUE TITLE
useLoadingValue error is typed Error not FirebaseError

### ISSUE THREAD

**Issue by r-bt** [CSFrequency/react-firebase-hooks#89]
Firstly, thanks for the great library :) I'm trying to use it with typescript but the return type from all the firebase hooks are returning errors typed as `Error` rather than `FirestoreError`. For example

```
// useCollection.ts

export type CollectionHook = LoadingHook<firestore.QuerySnapshot, Error>;

...

const { error, loading, reset, setError, setValue, value } = useLoadingValue<
    firestore.QuerySnapshot,
    Error
  >();
```

The error objects themselves though are Firebase Errors (as they have the `code` attribute).

This seems to have had been fixed in v1 with #18 but are now back to `Error` type in V2. Not sure if this was intentional or not, if not and it should be typed as `FirestoreError` I'd be more than happy to submit a pull request

**Comment by chrisbianca** [comment]
@r-bt Good spot. This looks like it was lost in some refactoring that was done. It will be included in the upcoming v3 release
