### ISSUE TITLE
Types in useAuthState are any

### ISSUE THREAD

**Issue by Ponjimon** [CSFrequency/react-firebase-hooks#92]
![image](https://user-images.githubusercontent.com/770632/99285200-88e5b580-2837-11eb-8b8d-3fd24c68cb14.png)
It seems that intellisense can't pick up the right types that are defined in the type definition of `useAuthState` resulting in the image above.

Am I doing something wrong here or is this some bug?

**Comment by Ponjimon** [comment]
Okay, it seems it's because `firebase` doesn't export a named export `User`.

So instead of `User` in the type definition, it should be `firebase.User`

**Comment by mdirolf** [comment]
I think this is fixed here: https://github.com/CSFrequency/react-firebase-hooks/pull/86

**Comment by chrisbianca** [comment]
As spotted by @mdirolf, this is fixed by #86 and will be included in the upcoming v3 release
