### ISSUE TITLE
useCollectionData query combination of where and orderBy do not work

### ISSUE THREAD

**Issue by joelmccauley** [CSFrequency/react-firebase-hooks#97]
query = messagesRef
      .where("users", "==", "1")
      .orderBy("createdAt");
  }
  const [messages] = useCollectionData(query, { idField: "id" });
  
  undefined
  
  :(

**Comment by joelmccauley** [comment]
Nevermind. Figured out it was indexing, but there was definitely no error reporting for it. Would be nice for the next guy I'm sure! Thanks!

**Comment by chrisbianca** [comment]
@joelmccauley Unfortunately Firebase doesn't expose this sort of error through the API which means there's no way of bringing it through the hooks library. Typically it will log a warning to the console if there is an indexing error.

**Comment by shamoons** [comment]
@joelmccauley - did you have to manually create a composite index? I thought Firebase would give you a link to create oen

**Comment by realBlueVein** [comment]
@joelmccauley  could you elaborate on how you addressed this issue? New to firebase but trying to figure out how to use .where and .orderBy in the same query. Something about indexing? Thanks.

**Comment by nicosayer** [comment]
> Nevermind. Figured out it was indexing, but there was definitely no error reporting for it. Would be nice for the next guy I'm sure! Thanks!

@joelmccauley Can you explain how you fixed this ? I have the same issue and don't understand what is going wrong.

**Comment by trungtin** [comment]
Leave it here for the next guy:

Open the Firestore dashboard, and in the Indexes tab, create a new composite index of all the fields that you want to filter by `where` and sort by `orderBy` together. Remember to select the order (ASC/DESC) you need.

Not sure why firebase-js-sdk doesn't report this error to the console; just an empty response.

**Comment by ishowta** [comment]
At least the latest firebase-js-sdk returns an error like `FirebaseError: The query requires an index. You can create it here: ...`.

```ts
  const [, , error] = useCollection(query)
  console.log(error)
```
