### ISSUE TITLE
What about tests?

### ISSUE THREAD

**Issue by dahmc** [CSFrequency/react-firebase-hooks#99]
I just wanted to have a look at how the tests are done to get some insights for my own hooks, and I couldn't find any.

There's also no test action in the scripts. 

Is that on purpose? Please don't take it as a 'wtf there are no tests', just genuinely curious. :)

**Comment by chrisbianca** [comment]
@dahmc This mostly comes down to "lack of time" to be able to introduce a proper test suite. I have some manual tests that I run over each change which whilst not particularly efficient, gives some confidence in the release.

I would be more than happy to receive contributions towards tests :)
